(function () {
  "use strict";

  const abilityOrder = ["passive", "q", "w", "e", "r", "utility"];

  const champions = {
    samira: {
      id: "samira",
      order: "01",
      release: "RELEASE",
      role: "MARKSMAN / ASSASSIN",
      controlCount: 112,
      menuSource: "samira_menu.lua",
      image: "./assets/champions/samira-splash.jpg",
      portrait: "./assets/champions/samira.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/samira-passive.png",
          items: [
            "Attack Hard CC Targets",
            "Fast S",
            "Insanity S",
            "Automatic R: Style S",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/samira-q.png",
          items: [
            "Melee / Ranged Q",
            "Prediction: Native / Reliable Trace / Hardlock Only",
            "Collision: Minion / Hero / Wall",
            "Q Flash",
            "Auto Q on Hard CC",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/samira-w.png",
          items: [
            "Block Evade Skillshots",
            "Block Targeted Spells",
            "Block Champion / Turret Missiles",
            "Block Critical Attacks",
            "Minimum Threat Danger",
            "Maximum Time to Impact",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/samira-e.png",
          items: [
            "E + Q",
            "Anti-Gapcloser",
            "Avoid Enemy Turrets",
            "Require Evade-safe Endpoint",
            "Maximum Enemies at Endpoint",
            "Endpoint Safety Range",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/samira-r.png",
          items: [
            "Automatic R: Style S",
            "Selected Target",
            "Target Health",
            "Minimum Targets",
            "Damage Estimate Shots",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Combo / Harass / Flee",
            "Lane Clear / Jungle Clear",
            "Last Hit",
            "Killsteal",
            "Manual Q / Manual E",
            "Draw / Diagnostics",
          ],
        },
      },
    },
    graves: {
      id: "graves",
      order: "02",
      release: "RELEASE",
      role: "MARKSMAN",
      controlCount: 144,
      menuSource: "graves_menu.lua",
      image: "./assets/champions/graves-splash.jpg",
      portrait: "./assets/champions/graves.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/graves-passive.png",
          items: [
            "Ammo-aware Q / E",
            "Reset Attack",
            "True Grit Refresh",
            "Combo Downtime",
            "Minimum True Grit Stacks",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/graves-q.png",
          items: [
            "Terrain Policy: Ignore / Prefer Wall / Require Wall",
            "Require Return Hit near Wall",
            "Quick Q during E Dash",
            "Prediction: Native / Reliable Trace / Hardlock Only",
            "Auto Q on Crowd Control",
            "Q when Minion blocks Attack",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/graves-w.png",
          items: [
            "Combo / Harass / Flee",
            "After Q / After Attack",
            "Anti-Melee",
            "Anti-Gapcloser",
            "Anti-Flash",
            "Reaction Whitelist",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/graves-e.png",
          items: [
            "Kite / Target / Cursor / Facing Cursor",
            "Reset Attack",
            "E + Q Wall Route",
            "Avoid Enemy Turret",
            "Require Evade-safe Endpoint",
            "Lane Clear / Jungle Clear",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/graves-r.png",
          items: [
            "Combo Backoff",
            "Auto Backoff at Low Health",
            "Killsteal",
            "Skip if Attack Kills",
            "Skip if Ally can Finish",
            "Prediction: Native / Reliable Trace / Hardlock Only",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Finish Routes",
            "AQE / AWQE / AQRE / AWRE / Explosive",
            "Flash Combo",
            "Reverse E + R / Reverse E + R + Flash",
            "Farm / Last Hit / Flee",
            "Draw / Diagnostics",
          ],
        },
      },
    },
    ezreal: {
      id: "ezreal",
      order: "03",
      release: "RELEASE",
      role: "MARKSMAN / MAGE",
      controlCount: 121,
      menuSource: "ezreal_menu.lua",
      image: "./assets/champions/ezreal-splash.jpg",
      portrait: "./assets/champions/ezreal.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/ezreal-passive.png",
          items: [
            "Keep Passive with Q",
            "Keep Passive from Stacks",
            "Refresh Passive below ms",
            "Passive Mana",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/ezreal-q.png",
          items: [
            "Combo / Harass / Auto Q / Killsteal",
            "Prediction: Native / Reliable Trace / Hardlock Only",
            "Q without Collision",
            "Wait for W Mark",
            "Protect Attack Windup",
            "Auto Q Whitelist",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/ezreal-w.png",
          items: [
            "Combo / Harass",
            "Use after Attack",
            "Use only if Q can Follow",
            "Calculate Turret / Epic Monster Collision",
            "Use on Turrets / Epic Monsters",
            "Prediction: Native / Reliable Trace / Hardlock Only",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/ezreal-e.png",
          items: [
            "Kite / Cursor / Target",
            "Combo E only for Lethal Route",
            "Flee / Anti-Melee / Anti-Gapcloser / Anti-Flash",
            "Anti-Skillshot",
            "Avoid Walls / Enemy Turrets",
            "Require Evade-safe Endpoint",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/ezreal-r.png",
          items: [
            "Combo / Killsteal / Manual R",
            "Auto R on Crowd Control",
            "Line AoE: Minimum Enemies Hit",
            "Steal Epic Monsters / Red / Blue Buff",
            "Protect Allied Buff Attempts",
            "Prediction: Native / Reliable Trace / Hardlock Only",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Selected Target / W-mark Focus",
            "Lane Clear / Jungle Clear / Last Hit",
            "Fast Clear / Last Hit Mode",
            "Passive Upkeep",
            "Farm / Flee",
            "Draw / Diagnostics",
          ],
        },
      },
    },
  };

  const translations = {
    "en-US": {
      metaTitle: "RiftReborn | Hanbot Champion AIO",
      metaDescription: "Explore RiftReborn releases for Samira, Graves, and Ezreal: champion-specific combat systems, safety checks, Prediction modes, and readable controls.",
      skipLink: "Skip to content",
      brandHome: "RiftReborn home",
      primaryNavigation: "Primary navigation",
      navReleases: "Releases",
      navSystem: "System",
      navDiscord: "Discord",
      languageLabel: "Language",
      heroEyebrow: "HANBOT CHAMPION AIO",
      heroLead: "Champion-specific Scripts built for deliberate control, safer decisions, and readable tuning.",
      heroPrimary: "Explore releases",
      heroSecondary: "Join Discord",
      heroReleaseLabel: "Champion releases",
      releaseEyebrow: "CHAMPION PROFILES",
      releaseTitle: "Three releases. Three distinct combat systems.",
      releaseBody: "Every profile keeps its own spell logic, priorities, safety checks, and menu surface.",
      rosterAria: "Champion selector",
      rosterLabel: "RELEASE ROSTER",
      rosterCountLabel: "ACTIVE RELEASES",
      profileEyebrow: "CHAMPION SYSTEM",
      controlsLabel: "CONTROLS",
      statusLabel: "STATUS",
      platformLabel: "PLATFORM",
      selectedSystemLabel: "SELECTED SYSTEM",
      menuSourceLabel: "MENU SOURCE",
      abilityNavigation: "Champion abilities",
      systemEyebrow: "THE SHARED CORE",
      systemTitle: "One contract. Champion logic stays distinct.",
      systemBody: "Shared infrastructure handles documented runtime contracts. Combat identity remains inside each champion.",
      pillarSdkTitle: "Documented SDK",
      pillarSdk: "Shared helpers follow documented object, Prediction, damage, and callback contracts.",
      pillarChampionTitle: "Champion Logic",
      pillarChampion: "Spells, ranges, priorities, and combat state stay isolated per champion.",
      pillarSafetyTitle: "Fail-closed Safety",
      pillarSafety: "Unsupported identifiers and unsafe routes are rejected instead of guessed.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Meet all three releases in one place.",
      discordBody: "Compare their systems, follow new releases, and continue the conversation in Discord.",
      discordAction: "Join Discord",
      legalDisclaimer: "RiftReborn is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games and all associated properties are trademarks or registered trademarks of Riot Games, Inc.",
      backToTop: "Back to top",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "the Desert Rose",
          intro: "Style-aware routes coordinate Q, W, E and R without flattening Samira into one fixed Combo.",
          alt: "Samira, the Desert Rose",
          abilities: { passive: "Daredevil Impulse", q: "Flair", w: "Blade Whirl", e: "Wild Rush", r: "Inferno Trigger", utility: "Combat Utility" },
          summaries: {
            passive: "Tracks Style and hard CC windows so automatic routes respect the conditions that make Samira's passive matter.",
            q: "Selects melee or ranged Q, then applies the configured Prediction and collision policy before committing.",
            w: "Filters incoming threats by type, danger, health, and impact time before spending Blade Whirl defensively.",
            e: "Builds E and E + Q routes around endpoint density, turret rules, target state, and Evade safety.",
            r: "Keeps automatic R behind verified Style S, target health, nearby enemies, and configurable damage estimates.",
            utility: "Connects Combo, Harass, Flee, Farm, Last Hit, Killsteal, manual keys, and Diagnostics around the spell core.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "the Outlaw",
          intro: "Ammo state, terrain returns, dash safety, and finish routes shape each Graves decision instead of a fixed cast order.",
          alt: "Graves, the Outlaw",
          abilities: { passive: "New Destiny", q: "End of the Line", w: "Smoke Screen", e: "Quickdraw", r: "Collateral Damage", utility: "Combat Utility" },
          summaries: {
            passive: "Feeds ammo, reload, attack reset, and True Grit state into the Q and E timing decisions.",
            q: "Evaluates wall policy, return-hit geometry, crowd control, collision, and Prediction before selecting a Q line.",
            w: "Combines Combo and Harass use with reaction rules for melee pressure, Gapcloser, Flash, and whitelisted targets.",
            e: "Chooses a dash direction, then rejects endpoints that violate enemy-density, turret, or Evade safety rules.",
            r: "Balances Combo backoff and Killsteal against attack damage, ally finish potential, recoil safety, and Prediction.",
            utility: "Adds finish logic, named special routes, Flash sequences, Farm, Last Hit, Flee, Draw, and Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "the Prodigal Explorer",
          intro: "W-Q sequencing, Q collision, defensive E endpoints, and distinct R routes keep Ezreal responsive to each fight.",
          alt: "Ezreal, the Prodigal Explorer",
          abilities: { passive: "Rising Spell Force", q: "Mystic Shot", w: "Essence Flux", e: "Arcane Shift", r: "Trueshot Barrage", utility: "Combat Utility" },
          summaries: {
            passive: "Refreshes Rising Spell Force with Q only when stack, expiry, mana, and target conditions support the upkeep route.",
            q: "Coordinates Combo, Harass, Auto Q, and Killsteal with W-mark focus, attack timing, collision, whitelist, and Prediction rules.",
            w: "Controls W-Q ordering and after-attack use while handling Turret and Epic Monster line checks as separate policies.",
            e: "Selects lethal, Flee, or defensive endpoints, then rejects walls, turrets, excess enemy density, and unsafe Evade routes.",
            r: "Keeps lethal, Killsteal, crowd-control, line-AoE, objective, and manual R routes behind their own range and safety gates.",
            utility: "Unifies selected and W-mark targeting with split Farm, Last Hit, passive upkeep, Draw, and Diagnostics controls.",
          },
        },
      },
    },

    "pt-BR": {
      metaTitle: "RiftReborn | AIO de campeões para Hanbot",
      metaDescription: "Conheça os releases de Samira, Graves e Ezreal no RiftReborn: sistemas de combate específicos, verificações de segurança, modos de Prediction e controles claros.",
      skipLink: "Ir para o conteúdo",
      brandHome: "Início do RiftReborn",
      primaryNavigation: "Navegação principal",
      navReleases: "Releases",
      navSystem: "Sistema",
      navDiscord: "Discord",
      languageLabel: "Idioma",
      heroEyebrow: "AIO DE CAMPEÕES PARA HANBOT",
      heroLead: "Scripts específicos por campeão, feitos para controle intencional, decisões mais seguras e ajustes fáceis de entender.",
      heroPrimary: "Explorar releases",
      heroSecondary: "Entrar no Discord",
      heroReleaseLabel: "Releases de campeões",
      releaseEyebrow: "PERFIS DE CAMPEÕES",
      releaseTitle: "Três releases. Três sistemas de combate distintos.",
      releaseBody: "Cada perfil preserva sua própria lógica de habilidades, prioridades, verificações de segurança e estrutura de menu.",
      rosterAria: "Seletor de campeão",
      rosterLabel: "LISTA DE RELEASES",
      rosterCountLabel: "RELEASES ATIVOS",
      profileEyebrow: "SISTEMA DO CAMPEÃO",
      controlsLabel: "CONTROLES",
      statusLabel: "STATUS",
      platformLabel: "PLATAFORMA",
      selectedSystemLabel: "SISTEMA SELECIONADO",
      menuSourceLabel: "MENU DE ORIGEM",
      abilityNavigation: "Habilidades do campeão",
      systemEyebrow: "O NÚCLEO COMPARTILHADO",
      systemTitle: "Um contrato. A lógica de cada campeão continua distinta.",
      systemBody: "A infraestrutura compartilhada cuida dos contratos documentados do runtime. A identidade de combate permanece em cada campeão.",
      pillarSdkTitle: "SDK documentado",
      pillarSdk: "Os helpers compartilhados seguem os contratos documentados de objetos, Prediction, dano e callbacks.",
      pillarChampionTitle: "Lógica do campeão",
      pillarChampion: "Habilidades, alcances, prioridades e estado de combate ficam isolados por campeão.",
      pillarSafetyTitle: "Segurança fail-closed",
      pillarSafety: "Identificadores sem suporte e rotas inseguras são rejeitados em vez de presumidos.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Encontre os três releases em um só lugar.",
      discordBody: "Compare os sistemas, acompanhe novos releases e continue a conversa no Discord.",
      discordAction: "Entrar no Discord",
      legalDisclaimer: "RiftReborn não é endossado pela Riot Games e não reflete as opiniões da Riot Games ou de qualquer pessoa oficialmente envolvida na produção ou gestão das propriedades da Riot Games. Riot Games e todas as propriedades associadas são marcas comerciais ou marcas registradas da Riot Games, Inc.",
      backToTop: "Voltar ao topo",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "a Rosa do Deserto",
          intro: "Rotas sensíveis ao Style coordenam Q, W, E e R sem reduzir Samira a um único Combo fixo.",
          alt: "Samira, a Rosa do Deserto",
          abilities: { passive: "Impulso Audacioso", q: "Talento Natural", w: "Voragem Afiada", e: "Ímpeto Indomável", r: "Gatilho Infernal", utility: "Utilidade de combate" },
          summaries: {
            passive: "Acompanha Style e janelas de hard CC para que as rotas automáticas respeitem as condições que tornam a passiva da Samira relevante.",
            q: "Escolhe entre Q corpo a corpo ou à distância e aplica a configuração de Prediction e colisão antes de conjurar.",
            w: "Filtra ameaças recebidas por tipo, perigo, vida e tempo de impacto antes de usar a Voragem Afiada defensivamente.",
            e: "Monta rotas de E e E + Q considerando densidade no destino, torres, estado do alvo e segurança do Evade.",
            r: "Mantém o R automático condicionado a Style S verificado, vida do alvo, inimigos próximos e estimativas de dano configuráveis.",
            utility: "Integra Combo, Harass, Flee, Farm, Last Hit, Killsteal, teclas manuais e Diagnostics ao núcleo de habilidades.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "o Foragido",
          intro: "Munição, retorno em terreno, segurança do dash e rotas de finalização orientam cada decisão do Graves.",
          alt: "Graves, o Foragido",
          abilities: { passive: "Nova Destino", q: "Fim da Linha", w: "Cortina de Fumaça", e: "Saque Rápido", r: "Efeito Colateral", utility: "Utilidade de combate" },
          summaries: {
            passive: "Leva munição, recarga, reset de ataque e True Grit para as decisões de tempo do Q e do E.",
            q: "Avalia política de parede, geometria do retorno, crowd control, colisão e Prediction antes de escolher a linha do Q.",
            w: "Combina uso em Combo e Harass com reações a pressão corpo a corpo, Gapcloser, Flash e alvos da whitelist.",
            e: "Escolhe a direção do dash e rejeita destinos que violem regras de densidade inimiga, torre ou segurança do Evade.",
            r: "Equilibra recuo no Combo e Killsteal com dano do ataque, finalização por aliado, segurança do recuo e Prediction.",
            utility: "Adiciona lógica de finalização, rotas especiais nomeadas, sequências com Flash, Farm, Last Hit, Flee, Draw e Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "o Explorador Pródigo",
          intro: "Sequências W-Q, colisão do Q, destinos defensivos do E e rotas distintas de R mantêm Ezreal responsivo a cada luta.",
          alt: "Ezreal, o Explorador Pródigo",
          abilities: { passive: "Feitiço do Poder Crescente", q: "Disparo Místico", w: "Fluxo Essencial", e: "Translocação Arcana", r: "Barragem Incendiária", utility: "Utilidade de combate" },
          summaries: {
            passive: "Renova o Feitiço do Poder Crescente com Q somente quando acúmulos, expiração, mana e alvo sustentam a rota de manutenção.",
            q: "Coordena Combo, Harass, Auto Q e Killsteal com foco na marca do W, tempo de ataque, colisão, whitelist e regras de Prediction.",
            w: "Controla a ordem W-Q e o uso após ataque, tratando verificações de linha para torres e monstros épicos como políticas separadas.",
            e: "Seleciona destinos letais, de Flee ou defensivos e rejeita paredes, torres, densidade excessiva e rotas inseguras para o Evade.",
            r: "Mantém rotas letais, de Killsteal, crowd control, line-AoE, objetivos e R manual atrás de limites próprios de alcance e segurança.",
            utility: "Une seleção de alvo e foco na marca do W com Farm separado, Last Hit, manutenção da passiva, Draw e Diagnostics.",
          },
        },
      },
    },

    "zh-CN": {
      metaTitle: "RiftReborn | Hanbot 英雄 AIO",
      metaDescription: "查看 RiftReborn 的莎弥拉、格雷福斯与伊泽瑞尔版本：独立英雄战斗系统、安全检查、Prediction 模式与清晰控制项。",
      skipLink: "跳到主要内容",
      brandHome: "RiftReborn 首页",
      primaryNavigation: "主导航",
      navReleases: "版本",
      navSystem: "系统",
      navDiscord: "Discord",
      languageLabel: "语言",
      heroEyebrow: "HANBOT 英雄 AIO",
      heroLead: "为每位英雄单独打造的 Script，强调可控决策、安全判断与清晰调校。",
      heroPrimary: "查看版本",
      heroSecondary: "加入 Discord",
      heroReleaseLabel: "英雄版本",
      releaseEyebrow: "英雄档案",
      releaseTitle: "三个版本，三套独立战斗系统。",
      releaseBody: "每份档案都保留各自的技能逻辑、优先级、安全检查与菜单结构。",
      rosterAria: "英雄选择器",
      rosterLabel: "版本名单",
      rosterCountLabel: "当前版本",
      profileEyebrow: "英雄系统",
      controlsLabel: "控制项",
      statusLabel: "状态",
      platformLabel: "平台",
      selectedSystemLabel: "当前系统",
      menuSourceLabel: "菜单来源",
      abilityNavigation: "英雄技能",
      systemEyebrow: "共享核心",
      systemTitle: "一套契约，英雄逻辑各自独立。",
      systemBody: "共享基础设施负责已记录的运行时契约，战斗特性仍保留在每位英雄内部。",
      pillarSdkTitle: "已记录的 SDK",
      pillarSdk: "共享 helper 遵循已记录的对象、Prediction、伤害与 callback 契约。",
      pillarChampionTitle: "英雄逻辑",
      pillarChampion: "技能、距离、优先级与战斗状态按英雄隔离。",
      pillarSafetyTitle: "默认拒绝安全策略",
      pillarSafety: "不支持的标识与不安全路线会被拒绝，而不是被猜测处理。",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "在同一处了解三个版本。",
      discordBody: "比较两套系统、跟进新版本，并在 Discord 继续交流。",
      discordAction: "加入 Discord",
      legalDisclaimer: "RiftReborn 未获 Riot Games 认可，也不代表 Riot Games 或任何正式参与 Riot Games 资产制作与管理人员的观点。Riot Games 及所有相关资产均为 Riot Games, Inc. 的商标或注册商标。",
      backToTop: "返回顶部",
      champions: {
        samira: {
          displayName: "莎弥拉",
          epithet: "沙漠玫瑰",
          intro: "围绕 Style 的路线协调 Q、W、E 与 R，而不是把莎弥拉简化成固定 Combo。",
          alt: "沙漠玫瑰 莎弥拉",
          abilities: { passive: "悍勇本色", q: "交火", w: "锋旋", e: "狂飙", r: "炼狱扳机", utility: "战斗功能" },
          summaries: {
            passive: "跟踪 Style 与 hard CC 窗口，让自动路线遵守莎弥拉被动的关键条件。",
            q: "在近战与远程 Q 之间选择，并在释放前应用设定的 Prediction 与碰撞策略。",
            w: "按类型、危险度、生命值和命中时间筛选威胁，再决定是否防御性使用 W。",
            e: "E 与 E + Q 路线会检查终点敌人数量、防御塔规则、目标状态与 Evade 安全。",
            r: "自动 R 必须满足已确认的 Style S、目标生命值、附近敌人数与可配置伤害估算。",
            utility: "将 Combo、Harass、Flee、Farm、Last Hit、Killsteal、手动按键与 Diagnostics 接入技能核心。",
          },
        },
        graves: {
          displayName: "格雷福斯",
          epithet: "法外狂徒",
          intro: "弹药状态、地形回弹、dash 安全与终结路线共同决定格雷福斯的每次行动。",
          alt: "法外狂徒 格雷福斯",
          abilities: { passive: "新命运", q: "穷途末路", w: "烟幕弹", e: "快速拔枪", r: "终极爆弹", utility: "战斗功能" },
          summaries: {
            passive: "把弹药、装填、攻击 reset 与 True Grit 状态纳入 Q 和 E 的时机判断。",
            q: "释放 Q 前评估墙体策略、回弹命中几何、crowd control、碰撞与 Prediction。",
            w: "结合 Combo、Harass 与针对近战压力、Gapcloser、Flash 和 whitelist 目标的反应规则。",
            e: "选择 dash 方向，并拒绝违反敌人密度、防御塔或 Evade 安全规则的终点。",
            r: "在 Combo 后撤与 Killsteal 之间权衡攻击伤害、队友收割、后坐安全与 Prediction。",
            utility: "加入终结逻辑、命名特殊路线、Flash 连段、Farm、Last Hit、Flee、Draw 与 Diagnostics。",
          },
        },
        ezreal: {
          displayName: "伊泽瑞尔",
          epithet: "探险家",
          intro: "W-Q 顺序、Q 碰撞、防御性 E 终点与独立 R 路线让伊泽瑞尔能针对每场战斗做出响应。",
          alt: "探险家 伊泽瑞尔",
          abilities: { passive: "咒能高涨", q: "秘术射击", w: "精华跃动", e: "奥术跃迁", r: "精准弹幕", utility: "战斗功能" },
          summaries: {
            passive: "仅在层数、剩余时间、法力与目标条件满足时，才用 Q 维持咒能高涨。",
            q: "通过 W 标记优先、攻击时机、碰撞、whitelist 与 Prediction 规则协调 Combo、Harass、Auto Q 和 Killsteal。",
            w: "控制 W-Q 顺序与攻击后使用，并把防御塔和史诗野怪的线路检查作为独立策略。",
            e: "选择致命、Flee 或防御终点，并拒绝墙体、防御塔、敌人过密与 Evade 不安全路线。",
            r: "致命、Killsteal、crowd control、line-AoE、目标争夺与手动 R 各自遵守独立距离和安全条件。",
            utility: "将选定目标与 W 标记优先，同分离的 Farm、Last Hit、被动维持、Draw 和 Diagnostics 控制整合。",
          },
        },
      },
    },

    "de-DE": {
      metaTitle: "RiftReborn | Hanbot Champion AIO",
      metaDescription: "Entdecke RiftReborn für Samira, Graves und Ezreal: champion-spezifische Kampfsysteme, Sicherheitsprüfungen, Prediction-Modi und klare Einstellungen.",
      skipLink: "Zum Inhalt springen",
      brandHome: "RiftReborn Startseite",
      primaryNavigation: "Hauptnavigation",
      navReleases: "Releases",
      navSystem: "System",
      navDiscord: "Discord",
      languageLabel: "Sprache",
      heroEyebrow: "HANBOT CHAMPION AIO",
      heroLead: "Champion-spezifische Scripts für bewusste Kontrolle, sicherere Entscheidungen und verständliche Einstellungen.",
      heroPrimary: "Releases ansehen",
      heroSecondary: "Discord beitreten",
      heroReleaseLabel: "Champion-Releases",
      releaseEyebrow: "CHAMPION-PROFILE",
      releaseTitle: "Drei Releases. Drei eigenständige Kampfsysteme.",
      releaseBody: "Jedes Profil behält seine eigene Zauberlogik, Prioritäten, Sicherheitsprüfungen und Menüstruktur.",
      rosterAria: "Champion-Auswahl",
      rosterLabel: "RELEASE-AUSWAHL",
      rosterCountLabel: "AKTIVE RELEASES",
      profileEyebrow: "CHAMPION-SYSTEM",
      controlsLabel: "EINSTELLUNGEN",
      statusLabel: "STATUS",
      platformLabel: "PLATTFORM",
      selectedSystemLabel: "GEWÄHLTES SYSTEM",
      menuSourceLabel: "MENÜQUELLE",
      abilityNavigation: "Champion-Fähigkeiten",
      systemEyebrow: "DER GEMEINSAME KERN",
      systemTitle: "Ein Vertrag. Eigenständige Champion-Logik.",
      systemBody: "Gemeinsame Infrastruktur verwaltet dokumentierte Laufzeitverträge. Die Kampfidentität bleibt beim jeweiligen Champion.",
      pillarSdkTitle: "Dokumentiertes SDK",
      pillarSdk: "Gemeinsame Helper folgen dokumentierten Objekt-, Prediction-, Schadens- und Callback-Verträgen.",
      pillarChampionTitle: "Champion-Logik",
      pillarChampion: "Fähigkeiten, Reichweiten, Prioritäten und Kampfstatus bleiben pro Champion isoliert.",
      pillarSafetyTitle: "Fail-closed-Sicherheit",
      pillarSafety: "Nicht unterstützte Bezeichner und unsichere Routen werden abgelehnt, statt sie zu erraten.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Alle drei Releases an einem Ort.",
      discordBody: "Vergleiche ihre Systeme, verfolge neue Releases und setze das Gespräch auf Discord fort.",
      discordAction: "Discord beitreten",
      legalDisclaimer: "RiftReborn wird nicht von Riot Games unterstützt und spiegelt weder die Ansichten von Riot Games noch von Personen wider, die offiziell an der Herstellung oder Verwaltung von Riot-Games-Eigentum beteiligt sind. Riot Games und alle zugehörigen Inhalte sind Marken oder eingetragene Marken von Riot Games, Inc.",
      backToTop: "Nach oben",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "die Wüstenrose",
          intro: "Style-bewusste Routen koordinieren Q, W, E und R, ohne Samira auf einen festen Combo zu reduzieren.",
          alt: "Samira, die Wüstenrose",
          abilities: { passive: "Draufgängerin", q: "Flair", w: "Klingenwirbel", e: "Ungezügelter Rausch", r: "Infernaler Abzug", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Verfolgt Style und hard-CC-Fenster, damit automatische Routen die Bedingungen von Samiras Passiv berücksichtigen.",
            q: "Wählt Nahkampf- oder Fernkampf-Q und wendet vor dem Einsatz die konfigurierte Prediction- und Kollisionsregel an.",
            w: "Filtert eingehende Bedrohungen nach Typ, Gefahr, Leben und Trefferzeit, bevor W defensiv eingesetzt wird.",
            e: "Plant E- und E + Q-Routen anhand von Gegnerdichte, Turmregeln, Zielstatus und Evade-Sicherheit.",
            r: "Automatisches R bleibt an bestätigten Style S, Zielleben, nahe Gegner und konfigurierbare Schadensschätzungen gebunden.",
            utility: "Verbindet Combo, Harass, Flee, Farm, Last Hit, Killsteal, manuelle Tasten und Diagnostics mit dem Zauberkern.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "der Gesetzlose",
          intro: "Munition, Terrain-Rückkehr, dash-Sicherheit und Finish-Routen formen jede Graves-Entscheidung.",
          alt: "Graves, der Gesetzlose",
          abilities: { passive: "Destiny Deluxe", q: "Endstation", w: "Nebelwand", e: "Schnelles Ziehen", r: "Kollateralschaden", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Bezieht Munition, Nachladen, Angriffs-reset und True Grit in das Timing von Q und E ein.",
            q: "Prüft Wandregel, Rückkehrtreffer, crowd control, Kollision und Prediction vor der Wahl einer Q-Linie.",
            w: "Verbindet Combo und Harass mit Reaktionen auf Nahkampfdruck, Gapcloser, Flash und Whitelist-Ziele.",
            e: "Wählt eine dash-Richtung und verwirft Endpunkte, die Gegnerdichte, Turm- oder Evade-Regeln verletzen.",
            r: "Wägt Combo-Backoff und Killsteal gegen Angriffsschaden, Ally-Finish, Rückstoßsicherheit und Prediction ab.",
            utility: "Ergänzt Finish-Logik, benannte Spezialrouten, Flash-Sequenzen, Farm, Last Hit, Flee, Draw und Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "der verwegene Forscher",
          intro: "W-Q-Abfolge, Q-Kollision, defensive E-Endpunkte und getrennte R-Routen lassen Ezreal auf jeden Kampf reagieren.",
          alt: "Ezreal, der verwegene Forscher",
          abilities: { passive: "Erhöhte Zaubermacht", q: "Mystischer Schuss", w: "Essenzflux", e: "Arkaner Sprung", r: "Energietrommelfeuer", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Erneuert Erhöhte Zaubermacht mit Q nur, wenn Stapel, Ablaufzeit, Mana und Ziel die Erhaltungsroute erlauben.",
            q: "Koordiniert Combo, Harass, Auto Q und Killsteal mit W-Mark-Fokus, Angriffstiming, Kollision, Whitelist und Prediction.",
            w: "Steuert die W-Q-Reihenfolge und Nutzung nach Angriffen; Turm- und Epic-Monster-Linien bleiben getrennte Regeln.",
            e: "Wählt tödliche, Flee- oder defensive Endpunkte und verwirft Wände, Türme, Gegnerdichte sowie unsichere Evade-Routen.",
            r: "Tödliche, Killsteal-, crowd-control-, line-AoE-, Ziel- und manuelle R-Routen besitzen eigene Reichweiten- und Sicherheitsregeln.",
            utility: "Verbindet ausgewählte und W-markierte Ziele mit getrenntem Farm, Last Hit, Passiv-Erhalt, Draw und Diagnostics.",
          },
        },
      },
    },

    "tr-TR": {
      metaTitle: "RiftReborn | Hanbot Şampiyon AIO",
      metaDescription: "Samira, Graves ve Ezreal için RiftReborn sürümlerini keşfet: şampiyona özel savaş sistemleri, güvenlik kontrolleri, Prediction modları ve anlaşılır ayarlar.",
      skipLink: "İçeriğe geç",
      brandHome: "RiftReborn ana sayfa",
      primaryNavigation: "Ana navigasyon",
      navReleases: "Sürümler",
      navSystem: "Sistem",
      navDiscord: "Discord",
      languageLabel: "Dil",
      heroEyebrow: "HANBOT ŞAMPİYON AIO",
      heroLead: "Kontrollü hareket, daha güvenli kararlar ve anlaşılır ayarlar için şampiyona özel Scripts.",
      heroPrimary: "Sürümleri incele",
      heroSecondary: "Discord'a katıl",
      heroReleaseLabel: "Şampiyon sürümleri",
      releaseEyebrow: "ŞAMPİYON PROFİLLERİ",
      releaseTitle: "Üç sürüm. Üç farklı savaş sistemi.",
      releaseBody: "Her profil kendi yetenek mantığını, önceliklerini, güvenlik kontrollerini ve menü yapısını korur.",
      rosterAria: "Şampiyon seçici",
      rosterLabel: "SÜRÜM KADROSU",
      rosterCountLabel: "AKTİF SÜRÜMLER",
      profileEyebrow: "ŞAMPİYON SİSTEMİ",
      controlsLabel: "AYARLAR",
      statusLabel: "DURUM",
      platformLabel: "PLATFORM",
      selectedSystemLabel: "SEÇİLİ SİSTEM",
      menuSourceLabel: "MENÜ KAYNAĞI",
      abilityNavigation: "Şampiyon yetenekleri",
      systemEyebrow: "ORTAK ÇEKİRDEK",
      systemTitle: "Tek sözleşme. Ayrı şampiyon mantığı.",
      systemBody: "Ortak altyapı belgelenmiş çalışma zamanı sözleşmelerini yönetir. Savaş kimliği her şampiyonun içinde kalır.",
      pillarSdkTitle: "Belgelenmiş SDK",
      pillarSdk: "Ortak helper'lar belgelenmiş nesne, Prediction, hasar ve callback sözleşmelerini izler.",
      pillarChampionTitle: "Şampiyon mantığı",
      pillarChampion: "Yetenekler, menziller, öncelikler ve savaş durumu şampiyon bazında ayrı kalır.",
      pillarSafetyTitle: "Fail-closed güvenlik",
      pillarSafety: "Desteklenmeyen tanımlar ve güvensiz rotalar tahmin edilmek yerine reddedilir.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Üç sürümü tek yerde keşfet.",
      discordBody: "Sistemleri karşılaştır, yeni sürümleri takip et ve Discord'da sohbete devam et.",
      discordAction: "Discord'a katıl",
      legalDisclaimer: "RiftReborn, Riot Games tarafından desteklenmez ve Riot Games'in ya da Riot Games varlıklarının üretimi veya yönetiminde resmi olarak yer alan kişilerin görüşlerini yansıtmaz. Riot Games ve ilgili tüm varlıklar Riot Games, Inc. şirketinin ticari veya tescilli markalarıdır.",
      backToTop: "Başa dön",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "Çöl Gülü",
          intro: "Style odaklı rotalar Q, W, E ve R'yi koordine eder; Samira'yı tek bir sabit Combo'ya indirgemez.",
          alt: "Samira, Çöl Gülü",
          abilities: { passive: "Deliduman", q: "Gösteriş", w: "Kılıç Girdabı", e: "Heyecan Dorukta", r: "Cehennem Tetiği", utility: "Savaş araçları" },
          summaries: {
            passive: "Style ve hard CC pencerelerini izleyerek otomatik rotaların Samira'nın pasif koşullarına uymasını sağlar.",
            q: "Yakın veya uzak Q seçer; kullanmadan önce ayarlanan Prediction ve çarpışma politikasını uygular.",
            w: "W'yu savunmada harcamadan önce tehditleri tür, tehlike, can ve çarpma süresine göre filtreler.",
            e: "E ve E + Q rotalarını varış noktası yoğunluğu, kule kuralları, hedef durumu ve Evade güvenliğiyle planlar.",
            r: "Otomatik R'yi doğrulanmış Style S, hedef canı, yakındaki rakipler ve ayarlanabilir hasar tahminlerine bağlar.",
            utility: "Combo, Harass, Flee, Farm, Last Hit, Killsteal, manuel tuşlar ve Diagnostics'i yetenek çekirdeğine bağlar.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "Kanun Kaçağı",
          intro: "Mermi durumu, arazi dönüşü, dash güvenliği ve bitirme rotaları her Graves kararını şekillendirir.",
          alt: "Graves, Kanun Kaçağı",
          abilities: { passive: "Yeni Kader", q: "Yolun Sonu", w: "Sis Perdesi", e: "Hızlı Tetik", r: "Parça Tesiri", utility: "Savaş araçları" },
          summaries: {
            passive: "Mermi, doldurma, saldırı reset'i ve True Grit durumunu Q ile E zamanlamasına taşır.",
            q: "Bir Q hattı seçmeden önce duvar politikasını, dönüş isabetini, crowd control, çarpışma ve Prediction'ı değerlendirir.",
            w: "Combo ve Harass kullanımını yakın dövüş baskısı, Gapcloser, Flash ve whitelist hedef tepkileriyle birleştirir.",
            e: "Bir dash yönü seçer; rakip yoğunluğu, kule veya Evade güvenlik kurallarını bozan varışları reddeder.",
            r: "Combo geri çekilmesi ve Killsteal'i saldırı hasarı, takım arkadaşı bitirişi, geri tepme güvenliği ve Prediction ile dengeler.",
            utility: "Bitirme mantığı, adlandırılmış özel rotalar, Flash dizileri, Farm, Last Hit, Flee, Draw ve Diagnostics ekler.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "Dahi Kâşif",
          intro: "W-Q sırası, Q çarpışması, savunma E varışları ve ayrı R rotaları Ezreal'in her savaşa tepki vermesini sağlar.",
          alt: "Ezreal, Dahi Kâşif",
          abilities: { passive: "Büyü Gücü Yükselişi", q: "Gizemli Atış", w: "Özüt Akışı", e: "Sihir Geçişi", r: "İsabet Dalgası", utility: "Savaş araçları" },
          summaries: {
            passive: "Büyü Gücü Yükselişi'ni Q ile yalnızca yük, bitiş süresi, mana ve hedef koşulları uygunsa yeniler.",
            q: "Combo, Harass, Auto Q ve Killsteal'i W işareti odağı, saldırı zamanı, çarpışma, whitelist ve Prediction ile koordine eder.",
            w: "W-Q sırasını ve saldırı sonrası kullanımı yönetirken kule ve Epic Monster hat kontrollerini ayrı politikalar olarak işler.",
            e: "Öldürücü, Flee veya savunma varışları seçer; duvar, kule, rakip yoğunluğu ve güvensiz Evade rotalarını reddeder.",
            r: "Öldürücü, Killsteal, crowd control, line-AoE, hedef ve manuel R rotalarını ayrı menzil ve güvenlik kurallarına bağlar.",
            utility: "Seçili ve W işaretli hedefleri ayrı Farm, Last Hit, pasif koruma, Draw ve Diagnostics kontrolleriyle birleştirir.",
          },
        },
      },
    },

    "pl-PL": {
      metaTitle: "RiftReborn | Hanbot Champion AIO",
      metaDescription: "Poznaj wydania RiftReborn dla Samiry, Gravesa i Ezreala: osobne systemy walki, kontrole bezpieczeństwa, tryby Prediction i czytelne ustawienia.",
      skipLink: "Przejdź do treści",
      brandHome: "Strona główna RiftReborn",
      primaryNavigation: "Nawigacja główna",
      navReleases: "Wydania",
      navSystem: "System",
      navDiscord: "Discord",
      languageLabel: "Język",
      heroEyebrow: "HANBOT CHAMPION AIO",
      heroLead: "Scripts tworzone osobno dla bohaterów: świadoma kontrola, bezpieczniejsze decyzje i czytelne ustawienia.",
      heroPrimary: "Zobacz wydania",
      heroSecondary: "Dołącz do Discorda",
      heroReleaseLabel: "Wydania bohaterów",
      releaseEyebrow: "PROFILE BOHATERÓW",
      releaseTitle: "Trzy wydania. Trzy odrębne systemy walki.",
      releaseBody: "Każdy profil zachowuje własną logikę umiejętności, priorytety, kontrole bezpieczeństwa i strukturę menu.",
      rosterAria: "Wybór bohatera",
      rosterLabel: "LISTA WYDAŃ",
      rosterCountLabel: "AKTYWNE WYDANIA",
      profileEyebrow: "SYSTEM BOHATERA",
      controlsLabel: "USTAWIENIA",
      statusLabel: "STATUS",
      platformLabel: "PLATFORMA",
      selectedSystemLabel: "WYBRANY SYSTEM",
      menuSourceLabel: "ŹRÓDŁO MENU",
      abilityNavigation: "Umiejętności bohatera",
      systemEyebrow: "WSPÓLNY RDZEŃ",
      systemTitle: "Jeden kontrakt. Odrębna logika bohaterów.",
      systemBody: "Wspólna infrastruktura obsługuje udokumentowane kontrakty runtime. Tożsamość walki pozostaje w module bohatera.",
      pillarSdkTitle: "Udokumentowane SDK",
      pillarSdk: "Wspólne helpery przestrzegają udokumentowanych kontraktów obiektów, Prediction, obrażeń i callbacków.",
      pillarChampionTitle: "Logika bohatera",
      pillarChampion: "Umiejętności, zasięgi, priorytety i stan walki są odizolowane dla każdego bohatera.",
      pillarSafetyTitle: "Bezpieczeństwo fail-closed",
      pillarSafety: "Nieobsługiwane identyfikatory i niebezpieczne trasy są odrzucane zamiast zgadywane.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Wszystkie trzy wydania w jednym miejscu.",
      discordBody: "Porównaj systemy, śledź nowe wydania i kontynuuj rozmowę na Discordzie.",
      discordAction: "Dołącz do Discorda",
      legalDisclaimer: "RiftReborn nie jest wspierany przez Riot Games i nie odzwierciedla poglądów Riot Games ani osób oficjalnie zaangażowanych w tworzenie lub zarządzanie własnością Riot Games. Riot Games i wszystkie powiązane elementy są znakami towarowymi lub zastrzeżonymi znakami towarowymi Riot Games, Inc.",
      backToTop: "Wróć na górę",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "Róża Pustyni",
          intro: "Trasy świadome Style koordynują Q, W, E i R, nie sprowadzając Samiry do jednego stałego Combo.",
          alt: "Samira, Róża Pustyni",
          abilities: { passive: "Chojracki Impuls", q: "Smykałka", w: "Wirujące Ostrze", e: "Dziki Pęd", r: "Piekielny Spust", utility: "Narzędzia walki" },
          summaries: {
            passive: "Śledzi Style i okna hard CC, aby automatyczne trasy respektowały warunki pasywu Samiry.",
            q: "Wybiera Q wręcz lub dystansowe, a przed użyciem stosuje ustawioną politykę Prediction i kolizji.",
            w: "Filtruje zagrożenia według typu, niebezpieczeństwa, zdrowia i czasu trafienia przed defensywnym użyciem W.",
            e: "Buduje trasy E oraz E + Q wokół liczby wrogów na końcu, zasad wież, stanu celu i bezpieczeństwa Evade.",
            r: "Automatyczne R wymaga potwierdzonego Style S, zdrowia celu, liczby pobliskich wrogów i ustawionej estymacji obrażeń.",
            utility: "Łączy Combo, Harass, Flee, Farm, Last Hit, Killsteal, ręczne klawisze i Diagnostics z rdzeniem umiejętności.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "Banita",
          intro: "Amunicja, powrót po terenie, bezpieczeństwo dash i trasy kończące kształtują każdą decyzję Gravesa.",
          alt: "Graves, Banita",
          abilities: { passive: "Nowy Los", q: "To Koniec!", w: "Zasłona Dymna", e: "Rozpęd", r: "Obrażenia Przypadkowe", utility: "Narzędzia walki" },
          summaries: {
            passive: "Włącza amunicję, przeładowanie, reset ataku i True Grit do decyzji o czasie Q oraz E.",
            q: "Sprawdza politykę ściany, trafienie powrotne, crowd control, kolizję i Prediction przed wyborem linii Q.",
            w: "Łączy użycie Combo i Harass z reakcjami na walkę wręcz, Gapcloser, Flash i cele z whitelist.",
            e: "Wybiera kierunek dash, po czym odrzuca punkty naruszające limity wrogów, zasady wież lub bezpieczeństwo Evade.",
            r: "Równoważy Combo backoff i Killsteal z obrażeniami ataku, wykończeniem przez sojusznika, odrzutem i Prediction.",
            utility: "Dodaje logikę kończenia, nazwane trasy specjalne, sekwencje Flash, Farm, Last Hit, Flee, Draw i Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "Odkrywca z Powołania",
          intro: "Kolejność W-Q, kolizja Q, defensywne punkty E i osobne trasy R pozwalają Ezrealowi reagować na każdą walkę.",
          alt: "Ezreal, Odkrywca z Powołania",
          abilities: { passive: "Wzmacniająca Siła Czarów", q: "Mistyczny Strzał", w: "Strumień Esencji", e: "Magiczne Przejście", r: "Celna Salwa", utility: "Narzędzia walki" },
          summaries: {
            passive: "Odświeża Wzmacniającą Siłę Czarów przez Q tylko wtedy, gdy ładunki, czas, mana i cel wspierają tę trasę.",
            q: "Koordynuje Combo, Harass, Auto Q i Killsteal z priorytetem znaku W, czasem ataku, kolizją, whitelist i Prediction.",
            w: "Kontroluje kolejność W-Q i użycie po ataku, rozdzielając sprawdzanie linii wież oraz Epic Monster.",
            e: "Wybiera śmiertelne, Flee lub defensywne punkty i odrzuca ściany, wieże, nadmiar wrogów oraz niebezpieczne trasy Evade.",
            r: "Trasy śmiertelne, Killsteal, crowd control, line-AoE, cele i ręczne R mają osobne reguły zasięgu oraz bezpieczeństwa.",
            utility: "Łączy wybrany cel i znak W z rozdzielonym Farm, Last Hit, utrzymaniem pasywu, Draw i Diagnostics.",
          },
        },
      },
    },
  };

  window.RIFTREBORN_CONTENT = Object.freeze({
    dataDragonVersion: "16.15.1",
    defaultLocale: "en-US",
    supportedLocales: Object.freeze(Object.keys(translations)),
    abilityOrder: Object.freeze(abilityOrder),
    lockedTerms: Object.freeze([
      "AIO", "Script", "Combo", "Harass", "Poke", "Killsteal", "Prediction", "Evade",
      "Flee", "Farm", "Last Hit", "Flash", "Gapcloser", "Draw", "Diagnostics",
    ]),
    champions: Object.freeze(champions),
    translations: Object.freeze(translations),
  });
})();
