(function () {
  "use strict";

  const abilityOrder = ["passive", "q", "w", "e", "r", "utility"];

  const champions = {
    samira: {
      id: "samira",
      order: "01",
      release: "RELEASE",
      role: "MARKSMAN / ASSASSIN",
      controlCount: 112,
      menuSource: "samira_menu.lua",
      image: "./assets/champions/samira-splash.jpg",
      portrait: "./assets/champions/samira.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/samira-passive.png",
          items: [
            "Attack Hard CC Targets",
            "Fast S",
            "Insanity S",
            "Automatic R: Style S",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/samira-q.png",
          items: [
            "Melee / Ranged Q",
            "Prediction: Native / Reliable Trace / Hardlock Only",
            "Collision: Minion / Hero / Wall",
            "Q Flash",
            "Auto Q on Hard CC",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/samira-w.png",
          items: [
            "Block Evade Skillshots",
            "Block Targeted Spells",
            "Block Champion / Turret Missiles",
            "Block Critical Attacks",
            "Minimum Threat Danger",
            "Maximum Time to Impact",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/samira-e.png",
          items: [
            "E + Q",
            "Anti-Gapcloser",
            "Avoid Enemy Turrets",
            "Require Evade-safe Endpoint",
            "Maximum Enemies at Endpoint",
            "Endpoint Safety Range",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/samira-r.png",
          items: [
            "Automatic R: Style S",
            "Selected Target",
            "Target Health",
            "Minimum Targets",
            "Damage Estimate Shots",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Combo / Harass / Flee",
            "Lane Clear / Jungle Clear",
            "Last Hit",
            "Killsteal",
            "Manual Q / Manual E",
            "Draw / Diagnostics",
          ],
        },
      },
    },
    graves: {
      id: "graves",
      order: "02",
      release: "RELEASE",
      role: "MARKSMAN",
      controlCount: 144,
      menuSource: "graves_menu.lua",
      image: "./assets/champions/graves-splash.jpg",
      portrait: "./assets/champions/graves.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/graves-passive.png",
          items: [
            "Ammo-aware Q / E",
            "Reset Attack",
            "True Grit Refresh",
            "Combo Downtime",
            "Minimum True Grit Stacks",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/graves-q.png",
          items: [
            "Terrain Policy: Ignore / Prefer Wall / Require Wall",
            "Require Return Hit near Wall",
            "Quick Q during E Dash",
            "Prediction: Native / Reliable Trace / Hardlock Only",
            "Auto Q on Crowd Control",
            "Q when Minion blocks Attack",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/graves-w.png",
          items: [
            "Combo / Harass / Flee",
            "After Q / After Attack",
            "Anti-Melee",
            "Anti-Gapcloser",
            "Anti-Flash",
            "Reaction Whitelist",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/graves-e.png",
          items: [
            "Kite / Target / Cursor / Facing Cursor",
            "Reset Attack",
            "E + Q Wall Route",
            "Avoid Enemy Turret",
            "Require Evade-safe Endpoint",
            "Lane Clear / Jungle Clear",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/graves-r.png",
          items: [
            "Combo Backoff",
            "Auto Backoff at Low Health",
            "Killsteal",
            "Skip if Attack Kills",
            "Skip if Ally can Finish",
            "Prediction: Native / Reliable Trace / Hardlock Only",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Finish Routes",
            "AQE / AWQE / AQRE / AWRE / Explosive",
            "Flash Combo",
            "Reverse E + R / Reverse E + R + Flash",
            "Farm / Last Hit / Flee",
            "Draw / Diagnostics",
          ],
        },
      },
    },
    ezreal: {
      id: "ezreal",
      order: "03",
      release: "RELEASE",
      role: "MARKSMAN / MAGE",
      controlCount: 121,
      menuSource: "ezreal_menu.lua",
      image: "./assets/champions/ezreal-splash.jpg",
      portrait: "./assets/champions/ezreal.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/ezreal-passive.png",
          items: [
            "Keep Passive with Q",
            "Keep Passive from Stacks",
            "Refresh Passive below ms",
            "Passive Mana",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/ezreal-q.png",
          items: [
            "Combo / Harass / Auto Q / Killsteal",
            "Prediction: Native / Reliable Trace / Hardlock Only",
            "Q without Collision",
            "Wait for W Mark",
            "Protect Attack Windup",
            "Auto Q Whitelist",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/ezreal-w.png",
          items: [
            "Combo / Harass",
            "Use after Attack",
            "Use only if Q can Follow",
            "Calculate Turret / Epic Monster Collision",
            "Use on Turrets / Epic Monsters",
            "Prediction: Native / Reliable Trace / Hardlock Only",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/ezreal-e.png",
          items: [
            "Kite / Cursor / Target",
            "Combo E only for Lethal Route",
            "Flee / Anti-Melee / Anti-Gapcloser / Anti-Flash",
            "Anti-Skillshot",
            "Avoid Walls / Enemy Turrets",
            "Require Evade-safe Endpoint",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/ezreal-r.png",
          items: [
            "Combo / Killsteal / Manual R",
            "Auto R on Crowd Control",
            "Line AoE: Minimum Enemies Hit",
            "Steal Epic Monsters / Red / Blue Buff",
            "Protect Allied Buff Attempts",
            "Prediction: Native / Reliable Trace / Hardlock Only",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Selected Target / W-mark Focus",
            "Lane Clear / Jungle Clear / Last Hit",
            "Fast Clear / Last Hit Mode",
            "Passive Upkeep",
            "Farm / Flee",
            "Draw / Diagnostics",
          ],
        },
      },
    },
    jinx: {
      id: "jinx",
      order: "04",
      release: "RELEASE",
      role: "MARKSMAN",
      controlCount: 108,
      menuSource: "jinx_menu.lua",
      image: "./assets/champions/jinx-splash.jpg",
      portrait: "./assets/champions/jinx.png",
      abilities: {
        passive: {
          key: "P",
          icon: "./assets/abilities/jinx-passive.png",
          items: [
            "Stack Tracking for Weapon Policy",
            "One Fishbones Shot at Full Stacks",
            "Pow-Pow above Attack Speed Gate",
            "Mana Gates for Combo / Harass",
            "Protect Attack Windup",
          ],
        },
        q: {
          key: "Q",
          icon: "./assets/abilities/jinx-q.png",
          items: [
            "Switch in Combo / Harass",
            "Weapon Policy: Automatic / Pow-Pow / Fishbones",
            "Automatic Range Switching",
            "Fishbones for Champion Splash",
            "Champion Splash Count >=",
            "Rocket Splash Radius",
          ],
        },
        w: {
          key: "W",
          icon: "./assets/abilities/jinx-w.png",
          items: [
            "Use in Combo / Harass / Flee",
            "Skip if Attacks Finish First",
            "Auto W on Crowd Control / Slow",
            "Killsteal",
            "Poke Champions while Clearing",
            "Prediction: RiftPred Hitchance",
          ],
        },
        e: {
          key: "E",
          icon: "./assets/abilities/jinx-e.png",
          items: [
            "Combat Placement: Crowd Control / Path Block / Always",
            "Extend along Target Path",
            "Auto E on Crowd Control",
            "Anti-Dash / Gapcloser",
            "Interrupt Channels / Trap Stasis",
            "Avoid Wall / Turret Placement",
          ],
        },
        r: {
          key: "R",
          icon: "./assets/abilities/jinx-r.png",
          items: [
            "Killsteal / Lethal R in Combo",
            "Use W + R Lethal Sequence",
            "Auto R on Crowd Control",
            "R for Multiple Enemies",
            "Block R near Enemy Champions",
            "Include Travel Regeneration",
          ],
        },
        utility: {
          key: "UTIL",
          icon: null,
          items: [
            "Keys & Toggles: Combo / Harass / Clear / Last Hit / Flee",
            "Manual W / Manual E / Manual R / Hold Fishbones",
            "Priority / Prefer Selected Target",
            "Lane / Jungle Fishbones & Last Hit",
            "RiftPred Shared Menu",
            "Drawings & Runtime Diagnostics",
          ],
        },
      },
    },
  };

  const translations = {
    "en-US": {
      metaTitle: "RiftPlus | Hanbot Champion AIO",
      metaDescription: "Explore RiftPlus releases for Samira, Graves, Ezreal, and Jinx: champion-specific combat systems, one shared Prediction engine, safety checks, and readable controls.",
      skipLink: "Skip to content",
      brandHome: "RiftPlus home",
      primaryNavigation: "Primary navigation",
      navReleases: "Releases",
      navPrediction: "Prediction",
      navCommunity: "Community",
      navSystem: "System",
      navDiscord: "Discord",
      languageLabel: "Language",
      heroEyebrow: "HANBOT CHAMPION AIO",
      heroLead: "Champion-specific Scripts on one shared Prediction engine, built for deliberate control and safer decisions.",
      heroPrimary: "Explore releases",
      heroSecondary: "Join Discord",
      heroReleaseLabel: "Champion releases",
      releaseEyebrow: "CHAMPION PROFILES",
      releaseTitle: "Four releases. Four distinct combat systems.",
      releaseBody: "Every profile keeps its own spell logic, priorities, safety checks, and menu surface on one shared Prediction engine.",
      predictionTitle: "One Prediction engine under every release.",
      predictionBody: "Every spell decision runs through the same documented Prediction contract: hitchance, traces, and safety gates stay consistent across profiles.",
      predictionAssetAria: "RiftPred prediction panel",
      rosterAria: "Champion selector",
      rosterLabel: "RELEASE ROSTER",
      rosterCountLabel: "ACTIVE RELEASES",
      profileEyebrow: "CHAMPION SYSTEM",
      controlsLabel: "CONTROLS",
      statusLabel: "STATUS",
      platformLabel: "PLATFORM",
      selectedSystemLabel: "SELECTED SYSTEM",
      menuSourceLabel: "MENU SOURCE",
      abilityNavigation: "Champion abilities",
      systemEyebrow: "THE SHARED CORE",
      systemTitle: "One contract. Champion logic stays distinct.",
      systemBody: "Shared infrastructure handles documented runtime contracts. Combat identity remains inside each champion.",
      pillarSdkTitle: "Documented SDK",
      pillarSdk: "Shared helpers follow documented object, Prediction, damage, and callback contracts.",
      pillarChampionTitle: "Champion Logic",
      pillarChampion: "Spells, ranges, priorities, and combat state stay isolated per champion.",
      pillarSafetyTitle: "Fail-closed Safety",
      pillarSafety: "Unsupported identifiers and unsafe routes are rejected instead of guessed.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Meet all four releases in one place.",
      discordBody: "Compare their systems, follow new releases, and continue the conversation in Discord.",
      discordAction: "Join Discord",
      communityEyebrow: "BUILT BY PLAYERS",
      communityTitle: "The AIO grows from the way you actually play.",
      communityBody: "Every feature starts with a player request. The community decides what earns a place in the next release.",
      communityFlowLabel: "Community release loop",
      communityStepSubmit: "Submit",
      communityStepSubmitBody: "Point to a champion and a feature, then describe what should change.",
      communityStepCurate: "Curate",
      communityStepCurateBody: "Requests are checked for scope, safety, and a clear runtime contract.",
      communityStepVote: "Vote",
      communityStepVoteBody: "When a request is ready, players vote yes on the exact behavior they want.",
      communityStepShip: "Ship",
      communityStepShipBody: "When yes reaches the threshold, the feature enters the next AIO release queue automatically.",
      communityFormEyebrow: "YOUR INPUT",
      communityFormTitle: "Suggest a change",
      communityFormBody: "Tell us where the current behavior misses your playstyle. Specific feedback gets reviewed faster.",
      communityChampionLabel: "Champion",
      communityFeatureLabel: "Feature",
      communityFeedbackLabel: "What should change?",
      communityFeedbackPlaceholder: "Example: wait for a confirmed hard CC window before Q Flash.",
      communityFormHint: "Submissions enter curation before voting.",
      communitySubmit: "Submit for curation",
      communityQueueEyebrow: "LIVE FEATURE BOARD",
      communityQueueTitle: "What players are shaping now",
      communityQueueBody: "Vote on behavior, not vague promises. A request only moves forward when the community says yes.",
      communityVoteYes: "Vote yes",
      communityVoted: "Voted",
      communityVotesLabel: "YES VOTES",
      communityStatusVoting: "VOTING",
      communityStatusReview: "IN CURATION",
      communityStatusRelease: "NEXT RELEASE",
      communityVotesToShip: "{votes} of {threshold} yes votes",
      communityFormSuccess: "Submitted for curation. The community can vote once it clears review.",
      communityFormEmpty: "Add a specific behavior before submitting.",
      communityProposalSamiraQ: "Players asked for a stricter Q Flash window after confirmed hard CC, with no cast when Prediction is uncertain.",
      communityProposalGravesE: "A safer E endpoint that prefers a wall return when the route keeps the next Q line available.",
      communityProposalEzrealW: "Keep W-Q available after an attack only when the follow-up line passes the selected Collision policy.",
      communityProposalSamiraW: "Review a tighter threat filter for W so defensive casts prioritize lethal skillshots over low-danger projectiles.",
      communityProposalJinxQ: "Players asked for a W + R lethal sequence that waits for a verified RiftPred hitchance window before committing.",
      legalDisclaimer: "RiftPlus is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games and all associated properties are trademarks or registered trademarks of Riot Games, Inc.",
      backToTop: "Back to top",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "the Desert Rose",
          intro: "Style-aware routes coordinate Q, W, E and R without flattening Samira into one fixed Combo.",
          alt: "Samira, the Desert Rose",
          abilities: { passive: "Daredevil Impulse", q: "Flair", w: "Blade Whirl", e: "Wild Rush", r: "Inferno Trigger", utility: "Combat Utility" },
          summaries: {
            passive: "Tracks Style and hard CC windows so automatic routes respect the conditions that make Samira's passive matter.",
            q: "Selects melee or ranged Q, then applies the configured Prediction and collision policy before committing.",
            w: "Filters incoming threats by type, danger, health, and impact time before spending Blade Whirl defensively.",
            e: "Builds E and E + Q routes around endpoint density, turret rules, target state, and Evade safety.",
            r: "Keeps automatic R behind verified Style S, target health, nearby enemies, and configurable damage estimates.",
            utility: "Connects Combo, Harass, Flee, Farm, Last Hit, Killsteal, manual keys, and Diagnostics around the spell core.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "the Outlaw",
          intro: "Ammo state, terrain returns, dash safety, and finish routes shape each Graves decision instead of a fixed cast order.",
          alt: "Graves, the Outlaw",
          abilities: { passive: "New Destiny", q: "End of the Line", w: "Smoke Screen", e: "Quickdraw", r: "Collateral Damage", utility: "Combat Utility" },
          summaries: {
            passive: "Feeds ammo, reload, attack reset, and True Grit state into the Q and E timing decisions.",
            q: "Evaluates wall policy, return-hit geometry, crowd control, collision, and Prediction before selecting a Q line.",
            w: "Combines Combo and Harass use with reaction rules for melee pressure, Gapcloser, Flash, and whitelisted targets.",
            e: "Chooses a dash direction, then rejects endpoints that violate enemy-density, turret, or Evade safety rules.",
            r: "Balances Combo backoff and Killsteal against attack damage, ally finish potential, recoil safety, and Prediction.",
            utility: "Adds finish logic, named special routes, Flash sequences, Farm, Last Hit, Flee, Draw, and Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "the Prodigal Explorer",
          intro: "W-Q sequencing, Q collision, defensive E endpoints, and distinct R routes keep Ezreal responsive to each fight.",
          alt: "Ezreal, the Prodigal Explorer",
          abilities: { passive: "Rising Spell Force", q: "Mystic Shot", w: "Essence Flux", e: "Arcane Shift", r: "Trueshot Barrage", utility: "Combat Utility" },
          summaries: {
            passive: "Refreshes Rising Spell Force with Q only when stack, expiry, mana, and target conditions support the upkeep route.",
            q: "Coordinates Combo, Harass, Auto Q, and Killsteal with W-mark focus, attack timing, collision, whitelist, and Prediction rules.",
            w: "Controls W-Q ordering and after-attack use while handling Turret and Epic Monster line checks as separate policies.",
            e: "Selects lethal, Flee, or defensive endpoints, then rejects walls, turrets, excess enemy density, and unsafe Evade routes.",
            r: "Keeps lethal, Killsteal, crowd-control, line-AoE, objective, and manual R routes behind their own range and safety gates.",
            utility: "Unifies selected and W-mark targeting with split Farm, Last Hit, passive upkeep, Draw, and Diagnostics controls.",
          },
        },
        jinx: {
          displayName: "Jinx",
          epithet: "the Loose Cannon",
          intro: "Weapon switching, Zap! gates, trap placement, and a global Rocket route coordinate without flattening Jinx into one fixed rotation.",
          alt: "Jinx, the Loose Cannon",
          abilities: { passive: "Get Excited!", q: "Switcheroo!", w: "Zap!", e: "Flame Chompers!", r: "Super Mega Death Rocket!", utility: "Combat Utility" },
          summaries: {
            passive: "Feeds stack, attack speed, and mana state into the weapon policy so Pow-Pow and Fishbones switch at the right moment.",
            q: "Picks Automatic, Pow-Pow, or Fishbones under combo, harassment, mana, splash, and attack speed gates before any shot.",
            w: "Keeps Zap! behind attack windows, mana gates, min and max range, crowd control reactions, and the RiftPred hitchance.",
            e: "Places Flame Chompers! for crowd control, path blocks, dash reactions, and channel interrupts with wall and turret avoidance.",
            r: "Routes Super Mega Death Rocket! behind killsteal, lethal W + R sequences, multi-enemy checks, safety radius, and regeneration math.",
            utility: "Connects keybinds, targeting, Farm routes, Fishbones last hits, Drawings, and Diagnostics around the spell core.",
          },
        },
      },
    },

    "pt-BR": {
      metaTitle: "RiftPlus | AIO de campeões para Hanbot",
      metaDescription: "Conheça os releases de Samira, Graves, Ezreal e Jinx no RiftPlus: sistemas de combate específicos, um motor de Prediction compartilhado, verificações de segurança e controles claros.",
      skipLink: "Ir para o conteúdo",
      brandHome: "Início do RiftPlus",
      primaryNavigation: "Navegação principal",
      navReleases: "Releases",
      navPrediction: "Prediction",
      navCommunity: "Comunidade",
      navSystem: "Sistema",
      navDiscord: "Discord",
      languageLabel: "Idioma",
      heroEyebrow: "AIO DE CAMPEÕES PARA HANBOT",
      heroLead: "Scripts específicos por campeão sobre um motor de Prediction compartilhado, feitos para controle intencional e decisões mais seguras.",
      heroPrimary: "Explorar releases",
      heroSecondary: "Entrar no Discord",
      heroReleaseLabel: "Releases de campeões",
      releaseEyebrow: "PERFIS DE CAMPEÕES",
      releaseTitle: "Quatro releases. Quatro sistemas de combate distintos.",
      releaseBody: "Cada perfil preserva sua própria lógica de habilidades, prioridades, verificações de segurança e estrutura de menu sobre um motor de Prediction compartilhado.",
      predictionTitle: "Um motor de Prediction sob cada release.",
      predictionBody: "Toda decisão de habilidade passa pelo mesmo contrato documentado de Prediction: hitchance, traces e verificações de segurança permanecem consistentes em todos os perfis.",
      predictionAssetAria: "Painel de Prediction do RiftPred",
      rosterAria: "Seletor de campeão",
      rosterLabel: "LISTA DE RELEASES",
      rosterCountLabel: "RELEASES ATIVOS",
      profileEyebrow: "SISTEMA DO CAMPEÃO",
      controlsLabel: "CONTROLES",
      statusLabel: "STATUS",
      platformLabel: "PLATAFORMA",
      selectedSystemLabel: "SISTEMA SELECIONADO",
      menuSourceLabel: "MENU DE ORIGEM",
      abilityNavigation: "Habilidades do campeão",
      systemEyebrow: "O NÚCLEO COMPARTILHADO",
      systemTitle: "Um contrato. A lógica de cada campeão continua distinta.",
      systemBody: "A infraestrutura compartilhada cuida dos contratos documentados do runtime. A identidade de combate permanece em cada campeão.",
      pillarSdkTitle: "SDK documentado",
      pillarSdk: "Os helpers compartilhados seguem os contratos documentados de objetos, Prediction, dano e callbacks.",
      pillarChampionTitle: "Lógica do campeão",
      pillarChampion: "Habilidades, alcances, prioridades e estado de combate ficam isolados por campeão.",
      pillarSafetyTitle: "Segurança fail-closed",
      pillarSafety: "Identificadores sem suporte e rotas inseguras são rejeitados em vez de presumidos.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Encontre os quatro releases em um só lugar.",
      discordBody: "Compare os sistemas, acompanhe novos releases e continue a conversa no Discord.",
      discordAction: "Entrar no Discord",
      communityEyebrow: "FEITO POR JOGADORES",
      communityTitle: "O AIO cresce do jeito que você realmente joga.",
      communityBody: "Toda feature começa com um pedido de jogador. A comunidade decide o que merece entrar no próximo release.",
      communityFlowLabel: "Ciclo de release da comunidade",
      communityStepSubmit: "Submit",
      communityStepSubmitBody: "Aponte o campeão e a feature, depois descreva o que deveria mudar.",
      communityStepCurate: "Curadoria",
      communityStepCurateBody: "Cada pedido passa por escopo, segurança e um contrato de runtime claro.",
      communityStepVote: "Votação",
      communityStepVoteBody: "Quando o pedido está pronto, os jogadores votam sim no comportamento exato.",
      communityStepShip: "Release",
      communityStepShipBody: "Quando os votos sim atingem a meta, a feature entra automaticamente na fila do próximo AIO release.",
      communityFormEyebrow: "SUA IDEIA",
      communityFormTitle: "Sugira uma mudança",
      communityFormBody: "Diga onde o comportamento atual não acompanha seu estilo de jogo. Feedback específico passa mais rápido pela revisão.",
      communityChampionLabel: "Campeão",
      communityFeatureLabel: "Feature",
      communityFeedbackLabel: "O que deveria mudar?",
      communityFeedbackPlaceholder: "Exemplo: esperar uma janela de hard CC confirmada antes do Q Flash.",
      communityFormHint: "Submissions passam por curadoria antes da votação.",
      communitySubmit: "Enviar para curadoria",
      communityQueueEyebrow: "QUADRO DE FEATURES",
      communityQueueTitle: "O que os jogadores estão moldando agora",
      communityQueueBody: "Vote no comportamento, não em promessas vagas. Um pedido só avança quando a comunidade diz sim.",
      communityVoteYes: "Votar sim",
      communityVoted: "Votado",
      communityVotesLabel: "VOTOS SIM",
      communityStatusVoting: "EM VOTAÇÃO",
      communityStatusReview: "EM CURADORIA",
      communityStatusRelease: "PRÓXIMO RELEASE",
      communityVotesToShip: "{votes} de {threshold} votos sim",
      communityFormSuccess: "Enviado para curadoria. A comunidade poderá votar quando passar pela revisão.",
      communityFormEmpty: "Descreva um comportamento específico antes de enviar.",
      communityProposalSamiraQ: "Jogadores pediram uma janela de Q Flash mais rígida após hard CC confirmado, sem conjurar quando a Prediction estiver incerta.",
      communityProposalGravesE: "Um destino de E mais seguro que prefira retorno na parede quando a rota mantém a próxima linha de Q disponível.",
      communityProposalEzrealW: "Manter W-Q disponível após um ataque somente quando a linha seguinte passar pela política de Collision selecionada.",
      communityProposalSamiraW: "Revisar um filtro de ameaças mais preciso para W, priorizando skillshots letais sobre projéteis de baixo perigo.",
      communityProposalJinxQ: "Jogadores pediram uma sequência letal de W + R que aguarde uma janela de hitchance verificada do RiftPred antes de conjurar.",
      legalDisclaimer: "RiftPlus não é endossado pela Riot Games e não reflete as opiniões da Riot Games ou de qualquer pessoa oficialmente envolvida na produção ou gestão das propriedades da Riot Games. Riot Games e todas as propriedades associadas são marcas comerciais ou marcas registradas da Riot Games, Inc.",
      backToTop: "Voltar ao topo",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "a Rosa do Deserto",
          intro: "Rotas sensíveis ao Style coordenam Q, W, E e R sem reduzir Samira a um único Combo fixo.",
          alt: "Samira, a Rosa do Deserto",
          abilities: { passive: "Impulso Audacioso", q: "Talento Natural", w: "Voragem Afiada", e: "Ímpeto Indomável", r: "Gatilho Infernal", utility: "Utilidade de combate" },
          summaries: {
            passive: "Acompanha Style e janelas de hard CC para que as rotas automáticas respeitem as condições que tornam a passiva da Samira relevante.",
            q: "Escolhe entre Q corpo a corpo ou à distância e aplica a configuração de Prediction e colisão antes de conjurar.",
            w: "Filtra ameaças recebidas por tipo, perigo, vida e tempo de impacto antes de usar a Voragem Afiada defensivamente.",
            e: "Monta rotas de E e E + Q considerando densidade no destino, torres, estado do alvo e segurança do Evade.",
            r: "Mantém o R automático condicionado a Style S verificado, vida do alvo, inimigos próximos e estimativas de dano configuráveis.",
            utility: "Integra Combo, Harass, Flee, Farm, Last Hit, Killsteal, teclas manuais e Diagnostics ao núcleo de habilidades.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "o Foragido",
          intro: "Munição, retorno em terreno, segurança do dash e rotas de finalização orientam cada decisão do Graves.",
          alt: "Graves, o Foragido",
          abilities: { passive: "Nova Destino", q: "Fim da Linha", w: "Cortina de Fumaça", e: "Saque Rápido", r: "Efeito Colateral", utility: "Utilidade de combate" },
          summaries: {
            passive: "Leva munição, recarga, reset de ataque e True Grit para as decisões de tempo do Q e do E.",
            q: "Avalia política de parede, geometria do retorno, crowd control, colisão e Prediction antes de escolher a linha do Q.",
            w: "Combina uso em Combo e Harass com reações a pressão corpo a corpo, Gapcloser, Flash e alvos da whitelist.",
            e: "Escolhe a direção do dash e rejeita destinos que violem regras de densidade inimiga, torre ou segurança do Evade.",
            r: "Equilibra recuo no Combo e Killsteal com dano do ataque, finalização por aliado, segurança do recuo e Prediction.",
            utility: "Adiciona lógica de finalização, rotas especiais nomeadas, sequências com Flash, Farm, Last Hit, Flee, Draw e Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "o Explorador Pródigo",
          intro: "Sequências W-Q, colisão do Q, destinos defensivos do E e rotas distintas de R mantêm Ezreal responsivo a cada luta.",
          alt: "Ezreal, o Explorador Pródigo",
          abilities: { passive: "Feitiço do Poder Crescente", q: "Disparo Místico", w: "Fluxo Essencial", e: "Translocação Arcana", r: "Barragem Incendiária", utility: "Utilidade de combate" },
          summaries: {
            passive: "Renova o Feitiço do Poder Crescente com Q somente quando acúmulos, expiração, mana e alvo sustentam a rota de manutenção.",
            q: "Coordena Combo, Harass, Auto Q e Killsteal com foco na marca do W, tempo de ataque, colisão, whitelist e regras de Prediction.",
            w: "Controla a ordem W-Q e o uso após ataque, tratando verificações de linha para torres e monstros épicos como políticas separadas.",
            e: "Seleciona destinos letais, de Flee ou defensivos e rejeita paredes, torres, densidade excessiva e rotas inseguras para o Evade.",
            r: "Mantém rotas letais, de Killsteal, crowd control, line-AoE, objetivos e R manual atrás de limites próprios de alcance e segurança.",
            utility: "Une seleção de alvo e foco na marca do W com Farm separado, Last Hit, manutenção da passiva, Draw e Diagnostics.",
          },
        },
        jinx: {
          displayName: "Jinx",
          epithet: "o Gatilho Desenfreado",
          intro: "Troca de armas, gates do Zap!, posicionamento de armadilhas e uma rota global de foguete se coordenam sem reduzir Jinx a uma rotação fixa.",
          alt: "Jinx, o Gatilho Desenfreado",
          abilities: { passive: "Anime-se!", q: "Trocando!", w: "Zap!", e: "Mordidinha Flamejante!", r: "Super Mega Míssil da Morte!", utility: "Utilidade de combate" },
          summaries: {
            passive: "Leva acúmulos, velocidade de ataque e mana para a política de armas, para que Pow-Pow e Fishbones troquem no momento certo.",
            q: "Escolhe Automatic, Pow-Pow ou Fishbones sob gates de combo, harass, mana, splash e velocidade de ataque antes de cada disparo.",
            w: "Mantém o Zap! atrás de janelas de ataque, gates de mana, alcance mínimo e máximo, reações a crowd control e o hitchance do RiftPred.",
            e: "Posiciona a Mordidinha Flamejante para crowd control, bloqueio de caminho, reações a dash e interrupção de canais, evitando paredes e torres.",
            r: "Direciona o Super Mega Míssil da Morte por killsteal, sequências letais de W + R, verificações de múltiplos inimigos, raio de segurança e regeneração.",
            utility: "Integra teclas, seleção de alvo, rotas de Farm, Last Hit com Fishbones, Drawings e Diagnostics ao núcleo de habilidades.",
          },
        },
      },
    },

    "zh-CN": {
      metaTitle: "RiftPlus | Hanbot 英雄 AIO",
      metaDescription: "查看 RiftPlus 的莎弥拉、格雷福斯、伊泽瑞尔与金克丝版本：独立英雄战斗系统、一套共享 Prediction 引擎、安全检查与清晰控制项。",
      skipLink: "跳到主要内容",
      brandHome: "RiftPlus 首页",
      primaryNavigation: "主导航",
      navReleases: "版本",
      navPrediction: "Prediction",
      navCommunity: "社区",
      navSystem: "系统",
      navDiscord: "Discord",
      languageLabel: "语言",
      heroEyebrow: "HANBOT 英雄 AIO",
      heroLead: "为每位英雄打造的 Script 运行在同一个 Prediction 引擎上，强调可控决策与更安全的判断。",
      heroPrimary: "查看版本",
      heroSecondary: "加入 Discord",
      heroReleaseLabel: "英雄版本",
      releaseEyebrow: "英雄档案",
      releaseTitle: "四个版本，四套独立战斗系统。",
      releaseBody: "每份档案都保留各自的技能逻辑、优先级、安全检查与菜单结构，全部运行在同一套 Prediction 引擎上。",
      predictionTitle: "所有版本共用一个 Prediction 引擎。",
      predictionBody: "每次技能决策都经过同一套已记录的 Prediction 契约：命中率、轨迹与安全门槛在所有英雄配置中保持一致。",
      predictionAssetAria: "RiftPred Prediction 面板",
      rosterAria: "英雄选择器",
      rosterLabel: "版本名单",
      rosterCountLabel: "当前版本",
      profileEyebrow: "英雄系统",
      controlsLabel: "控制项",
      statusLabel: "状态",
      platformLabel: "平台",
      selectedSystemLabel: "当前系统",
      menuSourceLabel: "菜单来源",
      abilityNavigation: "英雄技能",
      systemEyebrow: "共享核心",
      systemTitle: "一套契约，英雄逻辑各自独立。",
      systemBody: "共享基础设施负责已记录的运行时契约，战斗特性仍保留在每位英雄内部。",
      pillarSdkTitle: "已记录的 SDK",
      pillarSdk: "共享 helper 遵循已记录的对象、Prediction、伤害与 callback 契约。",
      pillarChampionTitle: "英雄逻辑",
      pillarChampion: "技能、距离、优先级与战斗状态按英雄隔离。",
      pillarSafetyTitle: "默认拒绝安全策略",
      pillarSafety: "不支持的标识与不安全路线会被拒绝，而不是被猜测处理。",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "在同一处了解四个版本。",
      discordBody: "比较两套系统、跟进新版本，并在 Discord 继续交流。",
      discordAction: "加入 Discord",
      communityEyebrow: "由玩家共同打造",
      communityTitle: "AIO 按照你的真实玩法持续成长。",
      communityBody: "每个功能都始于玩家请求。社区决定哪些内容值得进入下一个版本。",
      communityFlowLabel: "社区版本循环",
      communityStepSubmit: "提交",
      communityStepSubmitBody: "选择英雄与功能，然后描述你希望改变的行为。",
      communityStepCurate: "审核",
      communityStepCurateBody: "请求会先检查范围、安全性与清晰的运行时契约。",
      communityStepVote: "投票",
      communityStepVoteBody: "请求准备好后，玩家就具体行为投赞成票。",
      communityStepShip: "发布",
      communityStepShipBody: "赞成票达到门槛后，功能会自动进入下一个 AIO 版本队列。",
      communityFormEyebrow: "你的输入",
      communityFormTitle: "提出改动建议",
      communityFormBody: "告诉我们当前行为在哪些地方不符合你的玩法。具体反馈会更快进入审核。",
      communityChampionLabel: "英雄",
      communityFeatureLabel: "功能",
      communityFeedbackLabel: "希望改变什么？",
      communityFeedbackPlaceholder: "示例：在 Q Flash 前等待已确认的 hard CC 窗口。",
      communityFormHint: "提交内容会先审核，再进入投票。",
      communitySubmit: "提交审核",
      communityQueueEyebrow: "实时功能面板",
      communityQueueTitle: "玩家正在塑造的内容",
      communityQueueBody: "为具体行为投票，而不是模糊承诺。请求只有在社区投赞成票后才会继续。",
      communityVoteYes: "投赞成票",
      communityVoted: "已投票",
      communityVotesLabel: "赞成票",
      communityStatusVoting: "投票中",
      communityStatusReview: "审核中",
      communityStatusRelease: "下个版本",
      communityVotesToShip: "{votes} / {threshold} 张赞成票",
      communityFormSuccess: "已提交审核。通过审核后，社区即可投票。",
      communityFormEmpty: "提交前请描述具体行为。",
      communityProposalSamiraQ: "玩家希望在确认 hard CC 后使用更严格的 Q Flash 窗口，并在 Prediction 不确定时拒绝施放。",
      communityProposalGravesE: "更安全的 E 终点：当路线仍能保留下一条 Q 线时，优先选择靠墙回弹。",
      communityProposalEzrealW: "只有当后续线路通过所选 Collision 策略时，攻击后才保持 W-Q 可用。",
      communityProposalSamiraW: "审核更精确的 W 威胁过滤，让防御性施放优先处理致命 skillshot。",
      communityProposalJinxQ: "玩家希望 W + R 致命连招在施放前等待 RiftPred 验证过的命中率窗口。",
      legalDisclaimer: "RiftPlus 未获 Riot Games 认可，也不代表 Riot Games 或任何正式参与 Riot Games 资产制作与管理人员的观点。Riot Games 及所有相关资产均为 Riot Games, Inc. 的商标或注册商标。",
      backToTop: "返回顶部",
      champions: {
        samira: {
          displayName: "莎弥拉",
          epithet: "沙漠玫瑰",
          intro: "围绕 Style 的路线协调 Q、W、E 与 R，而不是把莎弥拉简化成固定 Combo。",
          alt: "沙漠玫瑰 莎弥拉",
          abilities: { passive: "悍勇本色", q: "交火", w: "锋旋", e: "狂飙", r: "炼狱扳机", utility: "战斗功能" },
          summaries: {
            passive: "跟踪 Style 与 hard CC 窗口，让自动路线遵守莎弥拉被动的关键条件。",
            q: "在近战与远程 Q 之间选择，并在释放前应用设定的 Prediction 与碰撞策略。",
            w: "按类型、危险度、生命值和命中时间筛选威胁，再决定是否防御性使用 W。",
            e: "E 与 E + Q 路线会检查终点敌人数量、防御塔规则、目标状态与 Evade 安全。",
            r: "自动 R 必须满足已确认的 Style S、目标生命值、附近敌人数与可配置伤害估算。",
            utility: "将 Combo、Harass、Flee、Farm、Last Hit、Killsteal、手动按键与 Diagnostics 接入技能核心。",
          },
        },
        graves: {
          displayName: "格雷福斯",
          epithet: "法外狂徒",
          intro: "弹药状态、地形回弹、dash 安全与终结路线共同决定格雷福斯的每次行动。",
          alt: "法外狂徒 格雷福斯",
          abilities: { passive: "新命运", q: "穷途末路", w: "烟幕弹", e: "快速拔枪", r: "终极爆弹", utility: "战斗功能" },
          summaries: {
            passive: "把弹药、装填、攻击 reset 与 True Grit 状态纳入 Q 和 E 的时机判断。",
            q: "释放 Q 前评估墙体策略、回弹命中几何、crowd control、碰撞与 Prediction。",
            w: "结合 Combo、Harass 与针对近战压力、Gapcloser、Flash 和 whitelist 目标的反应规则。",
            e: "选择 dash 方向，并拒绝违反敌人密度、防御塔或 Evade 安全规则的终点。",
            r: "在 Combo 后撤与 Killsteal 之间权衡攻击伤害、队友收割、后坐安全与 Prediction。",
            utility: "加入终结逻辑、命名特殊路线、Flash 连段、Farm、Last Hit、Flee、Draw 与 Diagnostics。",
          },
        },
        ezreal: {
          displayName: "伊泽瑞尔",
          epithet: "探险家",
          intro: "W-Q 顺序、Q 碰撞、防御性 E 终点与独立 R 路线让伊泽瑞尔能针对每场战斗做出响应。",
          alt: "探险家 伊泽瑞尔",
          abilities: { passive: "咒能高涨", q: "秘术射击", w: "精华跃动", e: "奥术跃迁", r: "精准弹幕", utility: "战斗功能" },
          summaries: {
            passive: "仅在层数、剩余时间、法力与目标条件满足时，才用 Q 维持咒能高涨。",
            q: "通过 W 标记优先、攻击时机、碰撞、whitelist 与 Prediction 规则协调 Combo、Harass、Auto Q 和 Killsteal。",
            w: "控制 W-Q 顺序与攻击后使用，并把防御塔和史诗野怪的线路检查作为独立策略。",
            e: "选择致命、Flee 或防御终点，并拒绝墙体、防御塔、敌人过密与 Evade 不安全路线。",
            r: "致命、Killsteal、crowd control、line-AoE、目标争夺与手动 R 各自遵守独立距离和安全条件。",
            utility: "将选定目标与 W 标记优先，同分离的 Farm、Last Hit、被动维持、Draw 和 Diagnostics 控制整合。",
          },
        },
        jinx: {
          displayName: "金克丝",
          epithet: "金克丝",
          intro: "武器切换、Zap! 门槛、陷阱摆放与全局火箭路线协同工作，而不是把金克丝压成固定连招。",
          alt: "金克丝",
          abilities: { passive: "罪恶快感", q: "枪炮交响曲！", w: "震荡电磁波！", e: "嚼火者手雷！", r: "超究极死神飞弹！", utility: "战斗功能" },
          summaries: {
            passive: "将层数、攻速与法力状态接入武器策略，让 Pow-Pow 与 Fishbones 在正确时机完成切换。",
            q: "在每次射击前根据连招、消耗、法力、溅射与攻速门槛选择 Automatic、Pow-Pow 或 Fishbones。",
            w: "让震荡电磁波！遵守攻击窗口、法力门槛、最小与最大距离、crowd control 反应与 RiftPred hitchance。",
            e: "将嚼火者手雷！用于 crowd control、路径封锁、dash 反应与打断引导，并避开墙体与防御塔。",
            r: "让超究极死神飞弹！遵循 killsteal、W + R 致命连招、多人判定、安全半径与回复计算。",
            utility: "将按键、目标选择、Farm 路线、Fishbones 补刀、Drawings 与 Diagnostics 接入技能核心。",
          },
        },
      },
    },

    "de-DE": {
      metaTitle: "RiftPlus | Hanbot Champion AIO",
      metaDescription: "Entdecke RiftPlus für Samira, Graves, Ezreal und Jinx: champion-spezifische Kampfsysteme, eine gemeinsame Prediction-Engine, Sicherheitsprüfungen und klare Einstellungen.",
      skipLink: "Zum Inhalt springen",
      brandHome: "RiftPlus Startseite",
      primaryNavigation: "Hauptnavigation",
      navReleases: "Releases",
      navPrediction: "Prediction",
      navCommunity: "Community",
      navSystem: "System",
      navDiscord: "Discord",
      languageLabel: "Sprache",
      heroEyebrow: "HANBOT CHAMPION AIO",
      heroLead: "Champion-spezifische Scripts auf einer gemeinsamen Prediction-Engine, für bewusste Kontrolle und sicherere Entscheidungen.",
      heroPrimary: "Releases ansehen",
      heroSecondary: "Discord beitreten",
      heroReleaseLabel: "Champion-Releases",
      releaseEyebrow: "CHAMPION-PROFILE",
      releaseTitle: "Vier Releases. Vier eigenständige Kampfsysteme.",
      releaseBody: "Jedes Profil behält seine eigene Zauberlogik, Prioritäten, Sicherheitsprüfungen und Menüstruktur auf einer gemeinsamen Prediction-Engine.",
      predictionTitle: "Eine Prediction-Engine für jedes Release.",
      predictionBody: "Jede Zauberentscheidung läuft durch denselben dokumentierten Prediction-Vertrag: Hitchance, Traces und Sicherheitsregeln bleiben über alle Profile konsistent.",
      predictionAssetAria: "RiftPred-Predictions-Panel",
      rosterAria: "Champion-Auswahl",
      rosterLabel: "RELEASE-AUSWAHL",
      rosterCountLabel: "AKTIVE RELEASES",
      profileEyebrow: "CHAMPION-SYSTEM",
      controlsLabel: "EINSTELLUNGEN",
      statusLabel: "STATUS",
      platformLabel: "PLATTFORM",
      selectedSystemLabel: "GEWÄHLTES SYSTEM",
      menuSourceLabel: "MENÜQUELLE",
      abilityNavigation: "Champion-Fähigkeiten",
      systemEyebrow: "DER GEMEINSAME KERN",
      systemTitle: "Ein Vertrag. Eigenständige Champion-Logik.",
      systemBody: "Gemeinsame Infrastruktur verwaltet dokumentierte Laufzeitverträge. Die Kampfidentität bleibt beim jeweiligen Champion.",
      pillarSdkTitle: "Dokumentiertes SDK",
      pillarSdk: "Gemeinsame Helper folgen dokumentierten Objekt-, Prediction-, Schadens- und Callback-Verträgen.",
      pillarChampionTitle: "Champion-Logik",
      pillarChampion: "Fähigkeiten, Reichweiten, Prioritäten und Kampfstatus bleiben pro Champion isoliert.",
      pillarSafetyTitle: "Fail-closed-Sicherheit",
      pillarSafety: "Nicht unterstützte Bezeichner und unsichere Routen werden abgelehnt, statt sie zu erraten.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Alle vier Releases an einem Ort.",
      discordBody: "Vergleiche ihre Systeme, verfolge neue Releases und setze das Gespräch auf Discord fort.",
      discordAction: "Discord beitreten",
      communityEyebrow: "VON SPIELERN ENTWICKELT",
      communityTitle: "Das AIO wächst mit deiner tatsächlichen Spielweise.",
      communityBody: "Jede Feature beginnt mit einem Spielerwunsch. Die Community entscheidet, was in den nächsten Release gehört.",
      communityFlowLabel: "Community-Release-Zyklus",
      communityStepSubmit: "Submit",
      communityStepSubmitBody: "Wähle Champion und Feature und beschreibe, was sich ändern soll.",
      communityStepCurate: "Kuratiert",
      communityStepCurateBody: "Anfragen werden auf Umfang, Sicherheit und einen klaren Runtime-Vertrag geprüft.",
      communityStepVote: "Abstimmen",
      communityStepVoteBody: "Sobald eine Anfrage bereit ist, stimmen Spieler über das genaue Verhalten ab.",
      communityStepShip: "Release",
      communityStepShipBody: "Erreicht das Ja die Schwelle, landet die Feature automatisch in der nächsten AIO-Release-Warteschlange.",
      communityFormEyebrow: "DEIN INPUT",
      communityFormTitle: "Änderung vorschlagen",
      communityFormBody: "Beschreibe, wo das aktuelle Verhalten deinen Spielstil verfehlt. Konkretes Feedback wird schneller geprüft.",
      communityChampionLabel: "Champion",
      communityFeatureLabel: "Feature",
      communityFeedbackLabel: "Was soll sich ändern?",
      communityFeedbackPlaceholder: "Beispiel: Vor Q Flash auf ein bestätigtes hard-CC-Fenster warten.",
      communityFormHint: "Submissions werden vor der Abstimmung kuratiert.",
      communitySubmit: "Zur Kuratierung senden",
      communityQueueEyebrow: "LIVE-FEATURE-BOARD",
      communityQueueTitle: "Was Spieler gerade formen",
      communityQueueBody: "Stimme über Verhalten ab, nicht über vage Versprechen. Eine Anfrage kommt nur mit einem Ja der Community weiter.",
      communityVoteYes: "Ja stimmen",
      communityVoted: "Abgestimmt",
      communityVotesLabel: "JA-STIMMEN",
      communityStatusVoting: "ABSTIMMUNG",
      communityStatusReview: "IN KURATIERUNG",
      communityStatusRelease: "NÄCHSTER RELEASE",
      communityVotesToShip: "{votes} von {threshold} Ja-Stimmen",
      communityFormSuccess: "Zur Kuratierung gesendet. Nach der Prüfung kann die Community abstimmen.",
      communityFormEmpty: "Beschreibe vor dem Senden ein konkretes Verhalten.",
      communityProposalSamiraQ: "Spieler wünschen ein strengeres Q-Flash-Fenster nach bestätigtem hard CC und keinen Cast bei unsicherer Prediction.",
      communityProposalGravesE: "Ein sicherer E-Endpunkt, der eine Wand-Rückkehr bevorzugt, wenn die nächste Q-Linie erhalten bleibt.",
      communityProposalEzrealW: "W-Q bleibt nach einem Angriff nur verfügbar, wenn die Folgelinie die gewählte Collision-Policy erfüllt.",
      communityProposalSamiraW: "Ein präziserer Bedrohungsfilter für W soll tödliche Skillshots vor Projektilen mit geringer Gefahr priorisieren.",
      communityProposalJinxQ: "Spieler wünschen eine tödliche W + R-Sequenz, die vor dem Einsatz auf ein verifiziertes RiftPred-Hitchance-Fenster wartet.",
      legalDisclaimer: "RiftPlus wird nicht von Riot Games unterstützt und spiegelt weder die Ansichten von Riot Games noch von Personen wider, die offiziell an der Herstellung oder Verwaltung von Riot-Games-Eigentum beteiligt sind. Riot Games und alle zugehörigen Inhalte sind Marken oder eingetragene Marken von Riot Games, Inc.",
      backToTop: "Nach oben",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "die Wüstenrose",
          intro: "Style-bewusste Routen koordinieren Q, W, E und R, ohne Samira auf einen festen Combo zu reduzieren.",
          alt: "Samira, die Wüstenrose",
          abilities: { passive: "Draufgängerin", q: "Flair", w: "Klingenwirbel", e: "Ungezügelter Rausch", r: "Infernaler Abzug", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Verfolgt Style und hard-CC-Fenster, damit automatische Routen die Bedingungen von Samiras Passiv berücksichtigen.",
            q: "Wählt Nahkampf- oder Fernkampf-Q und wendet vor dem Einsatz die konfigurierte Prediction- und Kollisionsregel an.",
            w: "Filtert eingehende Bedrohungen nach Typ, Gefahr, Leben und Trefferzeit, bevor W defensiv eingesetzt wird.",
            e: "Plant E- und E + Q-Routen anhand von Gegnerdichte, Turmregeln, Zielstatus und Evade-Sicherheit.",
            r: "Automatisches R bleibt an bestätigten Style S, Zielleben, nahe Gegner und konfigurierbare Schadensschätzungen gebunden.",
            utility: "Verbindet Combo, Harass, Flee, Farm, Last Hit, Killsteal, manuelle Tasten und Diagnostics mit dem Zauberkern.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "der Gesetzlose",
          intro: "Munition, Terrain-Rückkehr, dash-Sicherheit und Finish-Routen formen jede Graves-Entscheidung.",
          alt: "Graves, der Gesetzlose",
          abilities: { passive: "Destiny Deluxe", q: "Endstation", w: "Nebelwand", e: "Schnelles Ziehen", r: "Kollateralschaden", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Bezieht Munition, Nachladen, Angriffs-reset und True Grit in das Timing von Q und E ein.",
            q: "Prüft Wandregel, Rückkehrtreffer, crowd control, Kollision und Prediction vor der Wahl einer Q-Linie.",
            w: "Verbindet Combo und Harass mit Reaktionen auf Nahkampfdruck, Gapcloser, Flash und Whitelist-Ziele.",
            e: "Wählt eine dash-Richtung und verwirft Endpunkte, die Gegnerdichte, Turm- oder Evade-Regeln verletzen.",
            r: "Wägt Combo-Backoff und Killsteal gegen Angriffsschaden, Ally-Finish, Rückstoßsicherheit und Prediction ab.",
            utility: "Ergänzt Finish-Logik, benannte Spezialrouten, Flash-Sequenzen, Farm, Last Hit, Flee, Draw und Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "der verwegene Forscher",
          intro: "W-Q-Abfolge, Q-Kollision, defensive E-Endpunkte und getrennte R-Routen lassen Ezreal auf jeden Kampf reagieren.",
          alt: "Ezreal, der verwegene Forscher",
          abilities: { passive: "Erhöhte Zaubermacht", q: "Mystischer Schuss", w: "Essenzflux", e: "Arkaner Sprung", r: "Energietrommelfeuer", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Erneuert Erhöhte Zaubermacht mit Q nur, wenn Stapel, Ablaufzeit, Mana und Ziel die Erhaltungsroute erlauben.",
            q: "Koordiniert Combo, Harass, Auto Q und Killsteal mit W-Mark-Fokus, Angriffstiming, Kollision, Whitelist und Prediction.",
            w: "Steuert die W-Q-Reihenfolge und Nutzung nach Angriffen; Turm- und Epic-Monster-Linien bleiben getrennte Regeln.",
            e: "Wählt tödliche, Flee- oder defensive Endpunkte und verwirft Wände, Türme, Gegnerdichte sowie unsichere Evade-Routen.",
            r: "Tödliche, Killsteal-, crowd-control-, line-AoE-, Ziel- und manuelle R-Routen besitzen eigene Reichweiten- und Sicherheitsregeln.",
            utility: "Verbindet ausgewählte und W-markierte Ziele mit getrenntem Farm, Last Hit, Passiv-Erhalt, Draw und Diagnostics.",
          },
        },
        jinx: {
          displayName: "Jinx",
          epithet: "die Schießwütige",
          intro: "Waffenwechsel, Zap!-Gates, Fallenplatzierung und eine globale Raketenroute koordinieren sich, ohne Jinx auf eine feste Rotation zu reduzieren.",
          alt: "Jinx, die Schießwütige",
          abilities: { passive: "Ich werd' verrückt!", q: "Waffenwechsel!", w: "Brzl!", e: "Flammenfresser!", r: "Super-Mega-Todesrakete!", utility: "Kampfwerkzeuge" },
          summaries: {
            passive: "Bezieht Stapel, Angriffstempo und Mana in die Waffenpolitik ein, damit Pow-Pow und Fishbones im richtigen Moment wechseln.",
            q: "Wählt vor jedem Schuss Automatic, Pow-Pow oder Fishbones unter Combo-, Harass-, Mana-, Splash- und Tempo-Gates.",
            w: "Brzl! bleibt hinter Angriffsfenstern, Mana-Gates, Min- und Max-Reichweite, CC-Reaktionen und dem RiftPred-Hitchance.",
            e: "Platziert Flammenfresser! für crowd control, Pfadblockaden, Dash-Reaktionen und Kanalunterbrechungen mit Wand- und Turmvermeidung.",
            r: "Die Super-Mega-Todesrakete folgt Killsteal, tödlichen W + R-Sequenzen, Mehrfachgegner-Prüfungen, Sicherheitsradius und Regenerationsrechnung.",
            utility: "Verbindet Tasten, Zielauswahl, Farm-Routen, Fishbones-Last-Hits, Drawings und Diagnostics mit dem Zauberkern.",
          },
        },
      },
    },

    "tr-TR": {
      metaTitle: "RiftPlus | Hanbot Şampiyon AIO",
      metaDescription: "Samira, Graves, Ezreal ve Jinx için RiftPlus sürümlerini keşfet: şampiyona özel savaş sistemleri, tek ortak Prediction motoru, güvenlik kontrolleri ve anlaşılır ayarlar.",
      skipLink: "İçeriğe geç",
      brandHome: "RiftPlus ana sayfa",
      primaryNavigation: "Ana navigasyon",
      navReleases: "Sürümler",
      navPrediction: "Prediction",
      navCommunity: "Topluluk",
      navSystem: "Sistem",
      navDiscord: "Discord",
      languageLabel: "Dil",
      heroEyebrow: "HANBOT ŞAMPİYON AIO",
      heroLead: "Tek bir ortak Prediction motoru üzerinde şampiyona özel Scripts: kontrollü hareket ve daha güvenli kararlar.",
      heroPrimary: "Sürümleri incele",
      heroSecondary: "Discord'a katıl",
      heroReleaseLabel: "Şampiyon sürümleri",
      releaseEyebrow: "ŞAMPİYON PROFİLLERİ",
      releaseTitle: "Dört sürüm. Dört farklı savaş sistemi.",
      releaseBody: "Her profil kendi yetenek mantığını, önceliklerini, güvenlik kontrollerini ve menü yapısını ortak bir Prediction motoru üzerinde korur.",
      predictionTitle: "Her sürümün altında tek bir Prediction motoru.",
      predictionBody: "Her yetenek kararı aynı belgelenmiş Prediction sözleşmesinden geçer: hitchance, izler ve güvenlik eşikleri tüm profillerde tutarlı kalır.",
      predictionAssetAria: "RiftPred Prediction paneli",
      rosterAria: "Şampiyon seçici",
      rosterLabel: "SÜRÜM KADROSU",
      rosterCountLabel: "AKTİF SÜRÜMLER",
      profileEyebrow: "ŞAMPİYON SİSTEMİ",
      controlsLabel: "AYARLAR",
      statusLabel: "DURUM",
      platformLabel: "PLATFORM",
      selectedSystemLabel: "SEÇİLİ SİSTEM",
      menuSourceLabel: "MENÜ KAYNAĞI",
      abilityNavigation: "Şampiyon yetenekleri",
      systemEyebrow: "ORTAK ÇEKİRDEK",
      systemTitle: "Tek sözleşme. Ayrı şampiyon mantığı.",
      systemBody: "Ortak altyapı belgelenmiş çalışma zamanı sözleşmelerini yönetir. Savaş kimliği her şampiyonun içinde kalır.",
      pillarSdkTitle: "Belgelenmiş SDK",
      pillarSdk: "Ortak helper'lar belgelenmiş nesne, Prediction, hasar ve callback sözleşmelerini izler.",
      pillarChampionTitle: "Şampiyon mantığı",
      pillarChampion: "Yetenekler, menziller, öncelikler ve savaş durumu şampiyon bazında ayrı kalır.",
      pillarSafetyTitle: "Fail-closed güvenlik",
      pillarSafety: "Desteklenmeyen tanımlar ve güvensiz rotalar tahmin edilmek yerine reddedilir.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Dört sürümü tek yerde keşfet.",
      discordBody: "Sistemleri karşılaştır, yeni sürümleri takip et ve Discord'da sohbete devam et.",
      discordAction: "Discord'a katıl",
      communityEyebrow: "OYUNCULAR TARAFINDAN GELİŞTİRİLDİ",
      communityTitle: "AIO, gerçekten oynadığın şekle göre büyür.",
      communityBody: "Her özellik bir oyuncu isteğiyle başlar. Bir sonraki sürüme neyin gireceğine topluluk karar verir.",
      communityFlowLabel: "Topluluk sürüm döngüsü",
      communityStepSubmit: "Submit",
      communityStepSubmitBody: "Şampiyonu ve özelliği seç, ardından neyin değişmesi gerektiğini anlat.",
      communityStepCurate: "Kürasyon",
      communityStepCurateBody: "İstekler kapsam, güvenlik ve net bir runtime sözleşmesi için kontrol edilir.",
      communityStepVote: "Oy ver",
      communityStepVoteBody: "İstek hazır olduğunda oyuncular tam olarak istedikleri davranışa evet oyu verir.",
      communityStepShip: "Sürüm",
      communityStepShipBody: "Evet oyları eşiğe ulaştığında özellik otomatik olarak sonraki AIO sürüm kuyruğuna girer.",
      communityFormEyebrow: "SENİN GERİ BİLDİRİMİN",
      communityFormTitle: "Değişiklik öner",
      communityFormBody: "Mevcut davranışın oyun tarzına nerede uymadığını anlat. Net geri bildirim daha hızlı incelenir.",
      communityChampionLabel: "Şampiyon",
      communityFeatureLabel: "Özellik",
      communityFeedbackLabel: "Ne değişmeli?",
      communityFeedbackPlaceholder: "Örnek: Q Flash'ten önce doğrulanmış bir hard CC penceresini bekle.",
      communityFormHint: "Submit içerikleri oylamadan önce kürasyondan geçer.",
      communitySubmit: "Kürasyona gönder",
      communityQueueEyebrow: "CANLI ÖZELLİK PANOSU",
      communityQueueTitle: "Oyuncuların şu an şekillendirdiği şeyler",
      communityQueueBody: "Belirsiz vaatlere değil davranışa oy ver. Bir istek ancak topluluk evet dediğinde ilerler.",
      communityVoteYes: "Evet oyu ver",
      communityVoted: "Oy verildi",
      communityVotesLabel: "EVET OYLARI",
      communityStatusVoting: "OYLAMADA",
      communityStatusReview: "KÜRASYONDA",
      communityStatusRelease: "SONRAKİ SÜRÜM",
      communityVotesToShip: "{threshold} oyun {votes} tanesi evet",
      communityFormSuccess: "Kürasyona gönderildi. İncelemeden sonra topluluk oy verebilir.",
      communityFormEmpty: "Göndermeden önce belirli bir davranışı anlat.",
      communityProposalSamiraQ: "Oyuncular, doğrulanmış hard CC sonrasında daha sıkı bir Q Flash penceresi ve belirsiz Prediction durumunda cast edilmemesini istiyor.",
      communityProposalGravesE: "Sonraki Q hattını koruyan rotalarda duvar dönüşünü tercih eden daha güvenli bir E varış noktası.",
      communityProposalEzrealW: "Saldırıdan sonra W-Q yalnızca sonraki hat seçili Collision politikasından geçiyorsa kullanılabilir kalsın.",
      communityProposalSamiraW: "W için daha sıkı bir tehdit filtresi incelensin; savunma kullanımı düşük tehlikeli mermilerden önce ölümcül skillshot'ları seçsin.",
      communityProposalJinxQ: "Oyuncular, saldırıdan önce doğrulanmış bir RiftPred hitchance penceresi bekleyen W + R ölümcül dizisi istiyor.",
      legalDisclaimer: "RiftPlus, Riot Games tarafından desteklenmez ve Riot Games'in ya da Riot Games varlıklarının üretimi veya yönetiminde resmi olarak yer alan kişilerin görüşlerini yansıtmaz. Riot Games ve ilgili tüm varlıklar Riot Games, Inc. şirketinin ticari veya tescilli markalarıdır.",
      backToTop: "Başa dön",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "Çöl Gülü",
          intro: "Style odaklı rotalar Q, W, E ve R'yi koordine eder; Samira'yı tek bir sabit Combo'ya indirgemez.",
          alt: "Samira, Çöl Gülü",
          abilities: { passive: "Deliduman", q: "Gösteriş", w: "Kılıç Girdabı", e: "Heyecan Dorukta", r: "Cehennem Tetiği", utility: "Savaş araçları" },
          summaries: {
            passive: "Style ve hard CC pencerelerini izleyerek otomatik rotaların Samira'nın pasif koşullarına uymasını sağlar.",
            q: "Yakın veya uzak Q seçer; kullanmadan önce ayarlanan Prediction ve çarpışma politikasını uygular.",
            w: "W'yu savunmada harcamadan önce tehditleri tür, tehlike, can ve çarpma süresine göre filtreler.",
            e: "E ve E + Q rotalarını varış noktası yoğunluğu, kule kuralları, hedef durumu ve Evade güvenliğiyle planlar.",
            r: "Otomatik R'yi doğrulanmış Style S, hedef canı, yakındaki rakipler ve ayarlanabilir hasar tahminlerine bağlar.",
            utility: "Combo, Harass, Flee, Farm, Last Hit, Killsteal, manuel tuşlar ve Diagnostics'i yetenek çekirdeğine bağlar.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "Kanun Kaçağı",
          intro: "Mermi durumu, arazi dönüşü, dash güvenliği ve bitirme rotaları her Graves kararını şekillendirir.",
          alt: "Graves, Kanun Kaçağı",
          abilities: { passive: "Yeni Kader", q: "Yolun Sonu", w: "Sis Perdesi", e: "Hızlı Tetik", r: "Parça Tesiri", utility: "Savaş araçları" },
          summaries: {
            passive: "Mermi, doldurma, saldırı reset'i ve True Grit durumunu Q ile E zamanlamasına taşır.",
            q: "Bir Q hattı seçmeden önce duvar politikasını, dönüş isabetini, crowd control, çarpışma ve Prediction'ı değerlendirir.",
            w: "Combo ve Harass kullanımını yakın dövüş baskısı, Gapcloser, Flash ve whitelist hedef tepkileriyle birleştirir.",
            e: "Bir dash yönü seçer; rakip yoğunluğu, kule veya Evade güvenlik kurallarını bozan varışları reddeder.",
            r: "Combo geri çekilmesi ve Killsteal'i saldırı hasarı, takım arkadaşı bitirişi, geri tepme güvenliği ve Prediction ile dengeler.",
            utility: "Bitirme mantığı, adlandırılmış özel rotalar, Flash dizileri, Farm, Last Hit, Flee, Draw ve Diagnostics ekler.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "Dahi Kâşif",
          intro: "W-Q sırası, Q çarpışması, savunma E varışları ve ayrı R rotaları Ezreal'in her savaşa tepki vermesini sağlar.",
          alt: "Ezreal, Dahi Kâşif",
          abilities: { passive: "Büyü Gücü Yükselişi", q: "Gizemli Atış", w: "Özüt Akışı", e: "Sihir Geçişi", r: "İsabet Dalgası", utility: "Savaş araçları" },
          summaries: {
            passive: "Büyü Gücü Yükselişi'ni Q ile yalnızca yük, bitiş süresi, mana ve hedef koşulları uygunsa yeniler.",
            q: "Combo, Harass, Auto Q ve Killsteal'i W işareti odağı, saldırı zamanı, çarpışma, whitelist ve Prediction ile koordine eder.",
            w: "W-Q sırasını ve saldırı sonrası kullanımı yönetirken kule ve Epic Monster hat kontrollerini ayrı politikalar olarak işler.",
            e: "Öldürücü, Flee veya savunma varışları seçer; duvar, kule, rakip yoğunluğu ve güvensiz Evade rotalarını reddeder.",
            r: "Öldürücü, Killsteal, crowd control, line-AoE, hedef ve manuel R rotalarını ayrı menzil ve güvenlik kurallarına bağlar.",
            utility: "Seçili ve W işaretli hedefleri ayrı Farm, Last Hit, pasif koruma, Draw ve Diagnostics kontrolleriyle birleştirir.",
          },
        },
        jinx: {
          displayName: "Jinx",
          epithet: "Delifişek",
          intro: "Sila değiştirme, Zap! eşikleri, tuzak yerleşimi ve küresel bir roket rotası, Jinx'i sabit bir döngüye indirgemeden koordine olur.",
          alt: "Jinx, Delifişek",
          abilities: { passive: "Ay Çok Heyecanlı!", q: "Değiştir!", w: "Cızzt!", e: "Patlangaç!", r: "Manyak Güçlü Ölüm Roketi!", utility: "Savaş araçları" },
          summaries: {
            passive: "Sila politikasına yük, saldırı hızı ve mana durumunu aktarır; Pow-Pow ve Fishbones doğru anda değişir.",
            q: "Her atıştan önce Combo, Harass, mana, alan ve saldırı hızı eşikleri altında Automatic, Pow-Pow veya Fishbones seçer.",
            w: "Cızzt! saldırı pencereleri, mana eşikleri, min ve max menzil, crowd control tepkileri ve RiftPred hitchance arkasında kalır.",
            e: "Patlangaç!'ı crowd control, yol engelleme, dash tepkileri ve kanal kesme için yerleştirir; duvar ve kulelerden kaçınır.",
            r: "Manyak Güçlü Ölüm Roketi'ni killsteal, ölümcül W + R dizileri, çoklu rakip kontrolleri, güvenlik yarıçapı ve yenilenme hesabının arkasına alır.",
            utility: "Tuşları, hedef seçimini, Farm rotalarını, Fishbones last hit'lerini, Drawings ve Diagnostics'i yetenek çekirdeğine bağlar.",
          },
        },
      },
    },

    "pl-PL": {
      metaTitle: "RiftPlus | Hanbot Champion AIO",
      metaDescription: "Poznaj wersje RiftPlus dla Samiry, Gravesa, Ezreala i Jinx: systemy walki per bohater, jedna wspólna maszyna prediction, zabezpieczenia i przejrzyste ustawienia.",
      skipLink: "Przejdź do treści",
      brandHome: "Strona główna RiftPlus",
      primaryNavigation: "Nawigacja główna",
      navReleases: "Wersje",
      navPrediction: "Prediction",
      navCommunity: "Społeczność",
      navSystem: "System",
      navDiscord: "Discord",
      languageLabel: "Język",
      heroEyebrow: "HANBOT CHAMPION AIO",
      heroLead: "Skipty per bohater na jednej wspólnej maszynie prediction: świadoma kontrola i bezpieczniejsze decyzje.",
      heroPrimary: "Zobacz wydania",
      heroSecondary: "Dołącz do Discorda",
      heroReleaseLabel: "Wydania bohaterów",
      releaseEyebrow: "PROFILE BOHATERÓW",
      releaseTitle: "Cztery wydania. Cztery odrębne systemy walki.",
      releaseBody: "Każdy profil zachowuje własną logikę umiejętności, priorytety, kontrole bezpieczeństwa i strukturę menu na jednej wspólnej maszynie prediction.",
      predictionTitle: "Jedna maszyna prediction pod każdym wydaniem.",
      predictionBody: "Każda decyzja o umiejętności przechodzi przez ten sam udokumentowany kontrakt prediction: hitchance, trajektorie i progi bezpieczeństwa pozostają spójne we wszystkich profilach.",
      predictionAssetAria: "Panel prediction RiftPred",
      rosterAria: "Wybór bohatera",
      rosterLabel: "LISTA WYDAŃ",
      rosterCountLabel: "AKTYWNE WYDANIA",
      profileEyebrow: "SYSTEM BOHATERA",
      controlsLabel: "USTAWIENIA",
      statusLabel: "STATUS",
      platformLabel: "PLATFORMA",
      selectedSystemLabel: "WYBRANY SYSTEM",
      menuSourceLabel: "ŹRÓDŁO MENU",
      abilityNavigation: "Umiejętności bohatera",
      systemEyebrow: "WSPÓLNY RDZEŃ",
      systemTitle: "Jeden kontrakt. Odrębna logika bohaterów.",
      systemBody: "Wspólna infrastruktura obsługuje udokumentowane kontrakty runtime. Tożsamość walki pozostaje w module bohatera.",
      pillarSdkTitle: "Udokumentowane SDK",
      pillarSdk: "Wspólne helpery przestrzegają udokumentowanych kontraktów obiektów, Prediction, obrażeń i callbacków.",
      pillarChampionTitle: "Logika bohatera",
      pillarChampion: "Umiejętności, zasięgi, priorytety i stan walki są odizolowane dla każdego bohatera.",
      pillarSafetyTitle: "Bezpieczeństwo fail-closed",
      pillarSafety: "Nieobsługiwane identyfikatory i niebezpieczne trasy są odrzucane zamiast zgadywane.",
      discordEyebrow: "RIFTREBORN // DISCORD",
      discordTitle: "Poznaj wszystkie cztery wydania w jednym miejscu.",
      discordBody: "Porównaj systemy, śledź nowe wydania i kontynuuj rozmowę na Discordzie.",
      discordAction: "Dołącz do Discorda",
      communityEyebrow: "TWORZONE PRZEZ GRACZY",
      communityTitle: "AIO rośnie razem z tym, jak naprawdę grasz.",
      communityBody: "Każda funkcja zaczyna się od prośby gracza. Społeczność decyduje, co zasługuje na kolejny release.",
      communityFlowLabel: "Cykl release społeczności",
      communityStepSubmit: "Submit",
      communityStepSubmitBody: "Wskaż bohatera i funkcję, a potem opisz, co powinno się zmienić.",
      communityStepCurate: "Kuracja",
      communityStepCurateBody: "Prośby są sprawdzane pod kątem zakresu, bezpieczeństwa i jasnego kontraktu runtime.",
      communityStepVote: "Głosuj",
      communityStepVoteBody: "Gdy prośba jest gotowa, gracze głosują na konkretne zachowanie, którego chcą.",
      communityStepShip: "Release",
      communityStepShipBody: "Po osiągnięciu progu głosów na tak funkcja automatycznie trafia do kolejki następnego AIO release.",
      communityFormEyebrow: "TWÓJ WKŁAD",
      communityFormTitle: "Zaproponuj zmianę",
      communityFormBody: "Opisz, gdzie obecne zachowanie rozmija się z twoim stylem gry. Konkretne opinie są sprawdzane szybciej.",
      communityChampionLabel: "Bohater",
      communityFeatureLabel: "Funkcja",
      communityFeedbackLabel: "Co powinno się zmienić?",
      communityFeedbackPlaceholder: "Przykład: poczekaj na potwierdzone okno hard CC przed Q Flash.",
      communityFormHint: "Submissions trafiają do kuracji przed głosowaniem.",
      communitySubmit: "Wyślij do kuracji",
      communityQueueEyebrow: "TABLICA FUNKCJI LIVE",
      communityQueueTitle: "Co gracze kształtują teraz",
      communityQueueBody: "Głosuj na zachowanie, nie na mgliste obietnice. Prośba idzie dalej dopiero, gdy społeczność mówi tak.",
      communityVoteYes: "Głosuj na tak",
      communityVoted: "Zagłosowano",
      communityVotesLabel: "GŁOSY NA TAK",
      communityStatusVoting: "GŁOSOWANIE",
      communityStatusReview: "W KURACJI",
      communityStatusRelease: "NASTĘPNY RELEASE",
      communityVotesToShip: "{votes} z {threshold} głosów na tak",
      communityFormSuccess: "Wysłano do kuracji. Po sprawdzeniu społeczność będzie mogła zagłosować.",
      communityFormEmpty: "Przed wysłaniem opisz konkretne zachowanie.",
      communityProposalSamiraQ: "Gracze proszą o ciaśniejsze okno Q Flash po potwierdzonym hard CC i brak castu przy niepewnym Prediction.",
      communityProposalGravesE: "Bezpieczniejszy punkt E, który preferuje powrót od ściany, gdy trasa zachowuje następną linię Q.",
      communityProposalEzrealW: "W-Q pozostaje dostępne po ataku tylko wtedy, gdy kolejna linia spełnia wybraną politykę Collision.",
      communityProposalSamiraW: "Sprawdź dokładniejszy filtr zagrożeń dla W, który przed pociskami o niskim ryzyku wybiera śmiertelne skillshoty.",
      communityProposalJinxQ: "Gracze chcą śmiertelnej sekwencji W + R, która przed użyciem czeka na potwierdzone okno hitchance z RiftPred.",
      legalDisclaimer: "RiftPlus nie jest wspierany przez Riot Games i nie odzwierciedla poglądów Riot Games ani osób oficjalnie zaangażowanych w tworzenie lub zarządzanie własnością Riot Games. Riot Games i wszystkie powiązane elementy są znakami towarowymi lub zastrzeżonymi znakami towarowymi Riot Games, Inc.",
      backToTop: "Wróć na górę",
      champions: {
        samira: {
          displayName: "Samira",
          epithet: "Róża Pustyni",
          intro: "Trasy świadome Style koordynują Q, W, E i R, nie sprowadzając Samiry do jednego stałego Combo.",
          alt: "Samira, Róża Pustyni",
          abilities: { passive: "Chojracki Impuls", q: "Smykałka", w: "Wirujące Ostrze", e: "Dziki Pęd", r: "Piekielny Spust", utility: "Narzędzia walki" },
          summaries: {
            passive: "Śledzi Style i okna hard CC, aby automatyczne trasy respektowały warunki pasywu Samiry.",
            q: "Wybiera Q wręcz lub dystansowe, a przed użyciem stosuje ustawioną politykę Prediction i kolizji.",
            w: "Filtruje zagrożenia według typu, niebezpieczeństwa, zdrowia i czasu trafienia przed defensywnym użyciem W.",
            e: "Buduje trasy E oraz E + Q wokół liczby wrogów na końcu, zasad wież, stanu celu i bezpieczeństwa Evade.",
            r: "Automatyczne R wymaga potwierdzonego Style S, zdrowia celu, liczby pobliskich wrogów i ustawionej estymacji obrażeń.",
            utility: "Łączy Combo, Harass, Flee, Farm, Last Hit, Killsteal, ręczne klawisze i Diagnostics z rdzeniem umiejętności.",
          },
        },
        graves: {
          displayName: "Graves",
          epithet: "Banita",
          intro: "Amunicja, powrót po terenie, bezpieczeństwo dash i trasy kończące kształtują każdą decyzję Gravesa.",
          alt: "Graves, Banita",
          abilities: { passive: "Nowy Los", q: "To Koniec!", w: "Zasłona Dymna", e: "Rozpęd", r: "Obrażenia Przypadkowe", utility: "Narzędzia walki" },
          summaries: {
            passive: "Włącza amunicję, przeładowanie, reset ataku i True Grit do decyzji o czasie Q oraz E.",
            q: "Sprawdza politykę ściany, trafienie powrotne, crowd control, kolizję i Prediction przed wyborem linii Q.",
            w: "Łączy użycie Combo i Harass z reakcjami na walkę wręcz, Gapcloser, Flash i cele z whitelist.",
            e: "Wybiera kierunek dash, po czym odrzuca punkty naruszające limity wrogów, zasady wież lub bezpieczeństwo Evade.",
            r: "Równoważy Combo backoff i Killsteal z obrażeniami ataku, wykończeniem przez sojusznika, odrzutem i Prediction.",
            utility: "Dodaje logikę kończenia, nazwane trasy specjalne, sekwencje Flash, Farm, Last Hit, Flee, Draw i Diagnostics.",
          },
        },
        ezreal: {
          displayName: "Ezreal",
          epithet: "Odkrywca z Powołania",
          intro: "Kolejność W-Q, kolizja Q, defensywne punkty E i osobne trasy R pozwalają Ezrealowi reagować na każdą walkę.",
          alt: "Ezreal, Odkrywca z Powołania",
          abilities: { passive: "Wzmacniająca Siła Czarów", q: "Mistyczny Strzał", w: "Strumień Esencji", e: "Magiczne Przejście", r: "Celna Salwa", utility: "Narzędzia walki" },
          summaries: {
            passive: "Odświeża Wzmacniającą Siłę Czarów przez Q tylko wtedy, gdy ładunki, czas, mana i cel wspierają tę trasę.",
            q: "Koordynuje Combo, Harass, Auto Q i Killsteal z priorytetem znaku W, czasem ataku, kolizją, whitelist i Prediction.",
            w: "Kontroluje kolejność W-Q i użycie po ataku, rozdzielając sprawdzanie linii wież oraz Epic Monster.",
            e: "Wybiera śmiertelne, Flee lub defensywne punkty i odrzuca ściany, wieże, nadmiar wrogów oraz niebezpieczne trasy Evade.",
            r: "Trasy śmiertelne, Killsteal, crowd control, line-AoE, cele i ręczne R mają osobne reguły zasięgu oraz bezpieczeństwa.",
            utility: "Łączy wybrany cel i znak W z rozdzielonym Farm, Last Hit, utrzymaniem pasywu, Draw i Diagnostics.",
          },
        },
        jinx: {
          displayName: "Jinx",
          epithet: "Wystrzałowa Wariatka",
          intro: "Zmiana broni, progi Zap!, rozmieszczenie pułapek i globalna trasa rakiet koordynują się bez spłaszczania Jinx do jednej sekwencji.",
          alt: "Jinx, Wystrzałowa Wariatka",
          abilities: { passive: "Zabawmy się!", q: "Zmienianko!", w: "Bzzzyt!", e: "Ogniste Gryzaki!", r: "SuperMegaRakieta Śmierci!", utility: "Narzędzia walki" },
          summaries: {
            passive: "Przekazuje ładunki, tempo ataku i stan many do polityki broni, aby Pow-Pow i Fishbones zmieniały się we właściwym momencie.",
            q: "Przed każdym strzałem wybiera Automatic, Pow-Pow lub Fishbones pod progami Combo, Harass, many, splashu i tempa ataku.",
            w: "Bzzzyt! trzyma się okien ataku, progów many, minimalnego i maksymalnego zasięgu, reakcji na crowd control i hitchance RiftPred.",
            e: "Rozstawia Ogniste Gryzaki! pod crowd control, blokady tras, reakcje na dash i przerywanie kanałów, unikając ścian i wież.",
            r: "SuperMegaRakieta Śmierci! działa pod killsteal, śmiertelne sekwencje W + R, kontrole wielu wrogów, promień bezpieczeństwa i kalkulację regeneracji.",
            utility: "Podpina klawisze, wybór celu, trasy Farm, ostatnie trafienia Fishbones, Drawings i Diagnostics do rdzenia umiejętności.",
          },
        },
      },
    },
  };

  window.RIFTREBORN_CONTENT = Object.freeze({
    dataDragonVersion: "16.15.1",
    defaultLocale: "en-US",
    supportedLocales: Object.freeze(Object.keys(translations)),
    abilityOrder: Object.freeze(abilityOrder),
    lockedTerms: Object.freeze([
      "AIO", "Script", "Combo", "Harass", "Poke", "Killsteal", "Prediction", "Evade",
      "Flee", "Farm", "Last Hit", "Flash", "Gapcloser", "Draw", "Diagnostics",
    ]),
    champions: Object.freeze(champions),
    translations: Object.freeze(translations),
  });
})();
